import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es' | 'cn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.science": "The Science",
    "nav.benefits": "Benefits & Risks",
    "nav.guide": "Start Guide",
    "nav.getStarted": "Get Started",
    
    // Home
    "home.badge": "Science-Backed Nutrition",
    "home.title": "Unlock Metabolic Health: The Definitive Keto Guide",
    "home.subtitle": "A science-driven exploration of how the ketogenic diet can transform your metabolism — from molecular mechanisms inside your cells to real-world application for weight loss, type 2 diabetes, fatty liver, and metabolic syndrome.",
    "home.subtitle2": "Learn how to safely switch from sugar-dependence to fat-burning, improve insulin sensitivity, and support long-term health with evidence-based ketogenic strategies.",
    "home.cta.start": "Start Your Journey",
    "home.cta.science": "Explore the Science",
    "home.card.metabolic": "Metabolic Switch",
    "home.card.metabolic.desc": "Shift from glucose to fat metabolism for sustained energy.",
    "home.benefits.title": "More Than Just Weight Loss",
    "home.benefits.subtitle": "Modern research reveals that ketones are powerful signaling molecules that regulate critical cellular processes.",
    "home.card.cognitive": "Cognitive Function",
    "home.card.neuroprotection": "Neuroprotection",
    "home.card.neuroprotection.desc": "Ketones provide a stable fuel source for the brain, reducing reliance on glucose and potentially offering neuroprotective effects.",
    "home.card.metabolic_health": "Metabolic Health",
    "home.card.inflammation": "Inflammation Control",
    "home.card.inflammation.desc": "BHB directly inhibits the NLRP3 inflammasome, a key driver of chronic inflammation, promoting better long-term health.",
    "home.card.cardio": "Cardiovascular",
    "home.card.weight": "Weight Management",
    "home.card.weight.desc": "Superior appetite control and fat mobilization make keto a powerful tool for sustainable weight loss and metabolic syndrome reversal.",
    "home.how.title": "How the Ketogenic Diet Works",
    "home.how.desc": "In a standard Western diet, most cells run primarily on glucose. The ketogenic diet fundamentally shifts this metabolic paradigm. By restricting carbohydrate intake and increasing healthy fats, the body enters a state of ketosis.",
    "home.how.fuel": "Efficient Fuel",
    "home.how.fuel.desc": "Ketones are water-soluble and easily transported to the brain and muscles, providing a clean-burning energy source.",
    "home.how.hormones": "Hormonal Balance",
    "home.how.hormones.desc": "Lower insulin levels unlock stored fat for energy and improve insulin sensitivity over time.",
    "home.how.deepdive": "Read the Molecular Deep Dive",
    "home.cta.transform": "Ready to Transform Your Health?",
    "home.cta.transform.desc": "Get the complete guide to starting keto safely, managing side effects, and achieving long-term success.",
    "home.cta.check": "Check Indications",

    // Footer
    "footer.desc": "A comprehensive, science-backed resource for understanding and implementing the ketogenic diet safely and effectively.",
    "footer.content": "Content",
    "footer.legal": "Legal",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.disclaimer": "Medical Disclaimer",
    "footer.language": "Language",
    "footer.rights": "KetoGuide. All rights reserved. Information is for educational purposes only.",
    
    // Science Page
    "science.back": "Back to Home",
    "science.badge": "Molecular Mechanisms",
    "science.title": "How the Ketogenic Diet Works: A Molecular Deep Dive",
    "science.subtitle": "Understanding the metabolic shift from glucose to fat metabolism and the signaling power of ketone bodies.",
    "science.section1.title": "From Glucose to Fat Metabolism",
    "science.section1.p1": "In a typical Western diet, our cells primarily run on glucose. After a carbohydrate-rich meal, blood glucose rises, prompting the pancreas to release insulin. Insulin helps cells absorb glucose and store excess energy as glycogen and fat, while suppressing fat breakdown in adipose tissue.",
    "science.section1.p2": "The ketogenic diet fundamentally shifts this paradigm. By restricting carbohydrate intake to < 50 grams per day (typically 5–10% of total energy) and increasing fat intake to about 70–80% of calories, you lower insulin and force the body to seek an alternative fuel. Over several days, this drives the liver into ketogenesis, producing ketone bodies and initiating nutritional ketosis.",
    "science.card.triggers": "The Metabolic Shift Triggers",
    "science.card.triggers.desc": "Once carbohydrates are restricted and insulin falls, a cascade of metabolic events begins:",
    "science.card.insulin": "Lower Insulin",
    "science.card.insulin.desc1": "Blood glucose and insulin levels drop significantly.",
    "science.card.insulin.desc2": "Low insulin removes the \"brake\" on fat breakdown.",
    "science.card.insulin.desc3": "Cells become more sensitive to insulin over time, improving metabolic health.",
    "science.card.fat": "Fat Breakdown (Lipolysis)",
    "science.card.fat.desc1": "In adipose tissue, hormone-sensitive lipase (HSL) is activated.",
    "science.card.fat.desc2": "HSL breaks down stored triglycerides into free fatty acids (FFA) and glycerol.",
    "science.card.fat.desc3": "FFA travel through the bloodstream to the liver and other tissues as a major fuel source.",
    "science.card.ketone": "Ketone Production (Ketogenesis)",
    "science.card.ketone.desc1": "Inside the mitochondria of liver cells, free fatty acids undergo β-oxidation, generating acetyl-CoA.",
    "science.card.ketone.desc2": "Excess acetyl-CoA is routed into ketogenesis, producing ketone bodies: β-hydroxybutyrate (BHB), Acetoacetate (AcAc), and Acetone.",
    "science.card.ketone.desc3": "These ketones are then released into the bloodstream and become a central fuel for the brain, heart, and muscles.",
    "science.card.note": "Nutritional ketosis (BHB ~0.5–3.0 mmol/L) is not the same as diabetic ketoacidosis. In nutritional ketosis, pH remains normal, insulin is low but present, and the process is tightly regulated.",
    "science.section2.title": "Ketones as a Superior Fuel Source",
    "science.section2.p1": "Ketone bodies are water-soluble, which means they travel easily through the bloodstream and across cell membranes. Cells in muscle, heart, and brain express transporters (MCTs) that rapidly take up ketones. Inside the cell, ketones are converted back to acetyl-CoA and enter the Krebs cycle (TCA cycle) to produce ATP – the universal energy currency of the cell.",
    "science.section2.subtitle": "Efficient Brain Fuel & Metabolic Flexibility",
    "science.section2.p2": "A key advantage of ketosis is that the brain can obtain a significant share of its energy from ketones, reducing its reliance on glucose. This:",
    "science.section2.list1": "Smooths out blood sugar fluctuations",
    "science.section2.list2": "Can reduce \"energy crashes\" associated with high-carb eating",
    "science.section2.list3": "Helps explain why many people in ketosis report clearer thinking and more stable focus",
    "science.section2.flexibility": "This ability to switch between fuels — glucose when available, ketones when carbs are low — is called metabolic flexibility, and it’s a hallmark of a healthier metabolism.",
    "science.transport.title": "Visualizing Ketone Transport",
    "science.transport.1": "Generated in the liver from fatty acids",
    "science.transport.2": "Released into the bloodstream",
    "science.transport.3": "Rapidly transported via specific carriers to energy-hungry organs",
    "science.transport.4": "Converted to ATP inside mitochondria with impressive efficiency",
    "science.transport.note": "Unlike long-chain fatty acids, ketone bodies don’t require complex packaging in lipoproteins; they move freely in blood, making them a fast, clean, and accessible energy source.",
    "science.infographic.title": "Visualizing the Impact: High Insulin vs. Ketones",
    "science.infographic.desc": "This infographic illustrates the \"fuel switch\" in the brain. While high insulin levels can create metabolic debris, ketones provide a cleaner, more efficient fuel source that easily penetrates the blood-brain barrier.",
    "science.infographic.high_insulin": "High insulin / high glucose state",
    "science.infographic.high_insulin.1": "Frequent blood sugar spikes and crashes",
    "science.infographic.high_insulin.2": "Greater formation of glycation end products and oxidative stress",
    "science.infographic.high_insulin.3": "Potential \"metabolic clutter\" — inflammation and impaired cellular function over time",
    "science.infographic.ketone_state": "Ketone-supported state",
    "science.infographic.ketone_state.1": "Lower and more stable insulin",
    "science.infographic.ketone_state.2": "Ketones cross the blood–brain barrier easily and supply a steady, efficient fuel",
    "science.infographic.ketone_state.3": "Less oxidative stress per unit of energy in many contexts",
    "science.infographic.ketone_state.4": "A cleaner metabolic environment that may support long-term brain health",
    "science.section3.title": "More Than Just Fuel: Signaling Molecules",
    "science.section3.p1": "Modern research shows that ketones are not just passive energy carriers. They are bioactive signaling molecules that influence inflammation, gene expression, oxidative stress defenses, and metabolic pathways involved in aging and chronic disease.",
    "science.card.anti_inflammatory": "Anti-Inflammatory Effects",
    "science.card.anti_inflammatory.subtitle": "BHB and the NLRP3 inflammasome",
    "science.card.anti_inflammatory.desc1": "The NLRP3 inflammasome is an intracellular complex that amplifies inflammation and is implicated in conditions like obesity, type 2 diabetes, and cardiovascular disease.",
    "science.card.anti_inflammatory.desc2": "BHB directly inhibits NLRP3 activation, reducing production of inflammatory cytokines such as IL-1β and IL-18.",
    "science.card.anti_inflammatory.desc3": "This dampening of chronic, low-grade inflammation can support healthier blood vessels, metabolic tissues, and potentially brain function over time.",
    "science.card.anti_inflammatory.desc4": "In other words, ketones don’t just fuel cells — they help calm down inflammatory signaling at the molecular level.",
    "science.card.epigenetic": "Epigenetic Regulation",
    "science.card.epigenetic.subtitle": "BHB as an epigenetic signal",
    "science.card.epigenetic.desc1": "BHB also acts as:",
    "science.card.epigenetic.list1": "A histone deacetylase (HDAC) inhibitor",
    "science.card.epigenetic.list2": "A donor for histone β-hydroxybutyrylation",
    "science.card.epigenetic.desc2": "These processes modify how tightly DNA is packaged and how genes are expressed. Through these epigenetic mechanisms, BHB can:",
    "science.card.epigenetic.list3": "Upregulate genes involved in antioxidant defense and oxidative stress resistance",
    "science.card.epigenetic.list4": "Influence genes tied to energy metabolism and mitochondrial function",
    "science.card.epigenetic.list5": "Potentially support cellular longevity and resilience in tissues like the heart and brain",
    "science.card.epigenetic.desc3": "This is why ketogenic states are being explored not only for metabolic disorders, but also for their protective implications in cardiovascular and neurodegenerative diseases.",
    "science.references": "Scientific References",

    // Benefits Page
    "benefits.back": "Back to Home",
    "benefits.badge": "Indications & Contraindications",
    "benefits.title": "Is Keto Right for You?",
    "benefits.subtitle": "A balanced look at who can benefit most from the ketogenic diet and who should avoid it for safety reasons.",
    "benefits.section1.title": "Who Can Benefit?",
    "benefits.card.obesity": "Obesity & Metabolic Syndrome",
    "benefits.card.obesity.desc": "Powerful tool for achieving clinically meaningful weight loss and improving key metabolic markers like waist circumference, triglycerides, HDL cholesterol, and blood pressure.",
    "benefits.card.diabetes": "Type 2 Diabetes",
    "benefits.card.diabetes.desc": "Supervised ketogenic diets can lead to dramatic improvements in blood sugar control (HbA1c), reduce fasting glucose, and often allow for medication reduction.",
    "benefits.card.nafld": "NAFLD / MASLD",
    "benefits.card.nafld.desc": "Emerging research shows that ketogenic diets can reduce liver fat and lower liver enzymes in non-alcoholic fatty liver disease.",
    "benefits.card.pcos": "PCOS",
    "benefits.card.pcos.desc": "Shown to improve weight, insulin resistance, androgen levels, and menstrual regularity in women with Polycystic Ovary Syndrome.",
    "benefits.section2.title": "Absolute Contraindications",
    "benefits.contra.warning": "Do NOT start a ketogenic diet if you have:",
    "benefits.contra.1": "Known disorders of fatty acid oxidation (e.g., CPT-II deficiency)",
    "benefits.contra.2": "Defects in ketone body metabolism",
    "benefits.contra.3": "Acute or severe chronic pancreatitis",
    "benefits.contra.4": "Porphyria or severe liver failure",
    "benefits.section3.title": "Relative Contraindications",
    "benefits.caution": "These conditions require experienced medical supervision before and during the diet:",
    "benefits.caution.1": "Type 1 Diabetes",
    "benefits.caution.2": "Chronic Kidney Disease",
    "benefits.caution.3": "Pregnancy & Breastfeeding",
    "benefits.caution.4": "History of Eating Disorders",
    "benefits.caution.5": "Uncontrolled Dyslipidemia",
    "benefits.bottomline.title": "The Bottom Line",
    "benefits.bottomline.desc": "For people with obesity and insulin resistance, the ketogenic diet can be a highly effective tool, but it is crucial to consult with a healthcare professional before starting.",

    // Guide Page
    "guide.back": "Back to Home",
    "guide.badge": "Practical Application",
    "guide.title": "Getting Started with Keto: The First Two Weeks",
    "guide.subtitle": "A step-by-step guide to navigating the induction phase, managing side effects, and setting yourself up for long-term success.",
    "guide.step1.title": "Medical Preparation",
    "guide.step1.desc": "Before embarking on a ketogenic diet, it is best practice to:",
    "guide.step1.meds": "Review Medications",
    "guide.step1.meds.desc": "Discuss with your doctor, especially for diabetes and blood pressure meds.",
    "guide.step1.labs": "Baseline Lab Work",
    "guide.step1.labs.desc": "Fasting glucose, HbA1c, lipid panel, liver enzymes, and kidney function.",
    "guide.step2.title": "The Induction Phase (Days 1-14)",
    "guide.step2.expect": "What to Expect",
    "guide.step2.expect.desc": "During the first 3-14 days, your body transitions to ketosis. You will likely experience rapid water weight loss as glycogen stores are depleted.",
    "guide.step2.flu": "The \"Keto Flu\"",
    "guide.step2.flu.desc": "Transient symptoms like headache, fatigue, brain fog, and nausea are common but temporary.",
    "guide.step3.title": "Managing Side Effects",
    "guide.step3.hydrate": "Stay Hydrated",
    "guide.step3.hydrate.desc": "Drink plenty of water to replace lost fluids.",
    "guide.step3.electrolytes": "Electrolytes",
    "guide.step3.electrolytes.desc": "Supplement sodium, potassium, and magnesium.",
    "guide.step3.ease": "Ease Into It",
    "guide.step3.ease.desc": "Gradually reduce carbs if symptoms are severe.",
    "guide.longterm.title": "Long-Term Success & Pitfalls",
    "guide.longterm.p1": "The biggest challenge is sustainability. To succeed long-term, find your \"why,\" plan meals ahead, and connect with a supportive community.",
    "guide.longterm.p2": "Watch out for: Nutrient deficiencies (eat your veggies!), kidney stones (stay hydrated!), and elevated LDL cholesterol (monitor with your doctor)."
  },
  es: {
    // Navigation
    "nav.home": "Inicio",
    "nav.science": "La Ciencia",
    "nav.benefits": "Beneficios y Riesgos",
    "nav.guide": "Guía de Inicio",
    "nav.getStarted": "Empezar",
    
    // Home
    "home.badge": "Nutrición Respaldada por la Ciencia",
    "home.title": "Desbloquea tu Salud Metabólica: La Guía Definitiva Keto",
    "home.subtitle": "Una exploración científica de cómo la dieta cetogénica puede transformar su metabolismo, desde los mecanismos moleculares dentro de sus células hasta la aplicación en el mundo real para la pérdida de peso, la diabetes tipo 2, el hígado graso y el síndrome metabólico.",
    "home.subtitle2": "Aprenda a cambiar de forma segura de la dependencia del azúcar a la quema de grasa, mejorar la sensibilidad a la insulina y apoyar la salud a largo plazo con estrategias cetogénicas basadas en evidencia.",
    "home.cta.start": "Comienza tu Viaje",
    "home.cta.science": "Explora la Ciencia",
    "home.card.metabolic": "Cambio Metabólico",
    "home.card.metabolic.desc": "Cambia del metabolismo de glucosa al de grasa para energía sostenida.",
    "home.benefits.title": "Más Que Solo Pérdida de Peso",
    "home.benefits.subtitle": "La investigación moderna revela que las cetonas son poderosas moléculas de señalización que regulan procesos celulares críticos.",
    "home.card.cognitive": "Función Cognitiva",
    "home.card.neuroprotection": "Neuroprotección",
    "home.card.neuroprotection.desc": "Las cetonas proporcionan una fuente de combustible estable para el cerebro, reduciendo la dependencia de la glucosa y ofreciendo efectos neuroprotectores.",
    "home.card.metabolic_health": "Salud Metabólica",
    "home.card.inflammation": "Control de Inflamación",
    "home.card.inflammation.desc": "El BHB inhibe directamente el inflamasoma NLRP3, un impulsor clave de la inflamación crónica, promoviendo una mejor salud a largo plazo.",
    "home.card.cardio": "Cardiovascular",
    "home.card.weight": "Control de Peso",
    "home.card.weight.desc": "El control superior del apetito y la movilización de grasa hacen de keto una herramienta poderosa para la pérdida de peso sostenible.",
    "home.how.title": "Cómo Funciona la Dieta Cetogénica",
    "home.how.desc": "En una dieta occidental estándar, la mayoría de las células funcionan principalmente con glucosa. La dieta cetogénica cambia fundamentalmente este paradigma metabólico. Al restringir la ingesta de carbohidratos y aumentar las grasas saludables, el cuerpo entra en un estado de cetosis.",
    "home.how.fuel": "Combustible Eficiente",
    "home.how.fuel.desc": "Las cetonas son solubles en agua y se transportan fácilmente al cerebro y los músculos, proporcionando una fuente de energía limpia.",
    "home.how.hormones": "Equilibrio Hormonal",
    "home.how.hormones.desc": "Los niveles más bajos de insulina desbloquean la grasa almacenada para obtener energía y mejoran la sensibilidad a la insulina con el tiempo.",
    "home.how.deepdive": "Lee la Inmersión Profunda Molecular",
    "home.cta.transform": "¿Listo para Transformar tu Salud?",
    "home.cta.transform.desc": "Obtén la guía completa para comenzar keto de manera segura, manejar los efectos secundarios y lograr el éxito a largo plazo.",
    "home.cta.check": "Verificar Indicaciones",

    // Footer
    "footer.desc": "Un recurso integral respaldado por la ciencia para comprender e implementar la dieta cetogénica de manera segura y efectiva.",
    "footer.content": "Contenido",
    "footer.legal": "Legal",
    "footer.privacy": "Política de Privacidad",
    "footer.terms": "Términos de Servicio",
    "footer.disclaimer": "Descargo Médico",
    "footer.language": "Idioma",
    "footer.rights": "KetoGuide. Todos los derechos reservados. La información es solo para fines educativos.",

    // Science Page
    "science.back": "Volver al Inicio",
    "science.badge": "Mecanismos Moleculares",
    "science.title": "Cómo Funciona la Dieta Cetogénica: Una Inmersión Profunda Molecular",
    "science.subtitle": "Entendiendo el cambio metabólico de glucosa a metabolismo de grasas y el poder de señalización de los cuerpos cetónicos.",
    "science.section1.title": "De Glucosa a Metabolismo de Grasas",
    "science.section1.p1": "En una dieta occidental típica, nuestras células funcionan principalmente con glucosa. Después de una comida rica en carbohidratos, la glucosa en sangre aumenta, lo que hace que el páncreas libere insulina. La insulina ayuda a las células a absorber glucosa y almacenar el exceso de energía como glucógeno y grasa, mientras suprime la descomposición de la grasa en el tejido adiposo.",
    "science.section1.p2": "La dieta cetogénica cambia fundamentalmente este paradigma. Al restringir la ingesta de carbohidratos a < 50 gramos por día (típicamente 5–10% de la energía total) y aumentar la ingesta de grasas a aproximadamente 70–80% de las calorías, reduce la insulina y obliga al cuerpo a buscar un combustible alternativo. Durante varios días, esto impulsa al hígado a la cetogénesis, produciendo cuerpos cetónicos e iniciando la cetosis nutricional.",
    "science.card.triggers": "Desencadenantes del Cambio Metabólico",
    "science.card.triggers.desc": "Una vez que se restringen los carbohidratos y cae la insulina, comienza una cascada de eventos metabólicos:",
    "science.card.insulin": "Insulina Baja",
    "science.card.insulin.desc1": "Los niveles de glucosa e insulina en sangre bajan significativamente.",
    "science.card.insulin.desc2": "La insulina baja elimina el \"freno\" en la descomposición de la grasa.",
    "science.card.insulin.desc3": "Las células se vuelven más sensibles a la insulina con el tiempo, mejorando la salud metabólica.",
    "science.card.fat": "Descomposición de Grasa (Lipólisis)",
    "science.card.fat.desc1": "En el tejido adiposo, se activa la lipasa sensible a hormonas (HSL).",
    "science.card.fat.desc2": "La HSL descompone los triglicéridos almacenados en ácidos grasos libres (FFA) y glicerol.",
    "science.card.fat.desc3": "Los FFA viajan a través del torrente sanguíneo al hígado y otros tejidos como una fuente importante de combustible.",
    "science.card.ketone": "Producción de Cetonas (Cetogénesis)",
    "science.card.ketone.desc1": "Dentro de las mitocondrias de las células hepáticas, los ácidos grasos libres sufren β-oxidación, generando acetil-CoA.",
    "science.card.ketone.desc2": "El exceso de acetil-CoA se dirige a la cetogénesis, produciendo cuerpos cetónicos: β-hidroxibutirato (BHB), Acetoacetato (AcAc) y Acetona.",
    "science.card.ketone.desc3": "Estas cetonas se liberan luego al torrente sanguíneo y se convierten en un combustible central para el cerebro, el corazón y los músculos.",
    "science.card.note": "La cetosis nutricional (BHB ~0.5–3.0 mmol/L) no es lo mismo que la cetoacidosis diabética. En la cetosis nutricional, el pH permanece normal, la insulina es baja pero presente, y el proceso está estrictamente regulado.",
    "science.section2.title": "Cetonas como Fuente de Combustible Superior",
    "science.section2.p1": "Los cuerpos cetónicos son solubles en agua, lo que significa que viajan fácilmente a través del torrente sanguíneo y a través de las membranas celulares. Las células en el músculo, el corazón y el cerebro expresan transportadores (MCT) que absorben rápidamente las cetonas. Dentro de la célula, las cetonas se convierten nuevamente en acetil-CoA y entran en el ciclo de Krebs (ciclo TCA) para producir ATP, la moneda de energía universal de la célula.",
    "science.section2.subtitle": "Combustible Cerebral Eficiente y Flexibilidad Metabólica",
    "science.section2.p2": "Una ventaja clave de la cetosis es que el cerebro puede obtener una parte significativa de su energía de las cetonas, reduciendo su dependencia de la glucosa. Esto:",
    "science.section2.list1": "Suaviza las fluctuaciones de azúcar en sangre",
    "science.section2.list2": "Puede reducir los \"bajones de energía\" asociados con la alimentación alta en carbohidratos",
    "science.section2.list3": "Ayuda a explicar por qué muchas personas en cetosis reportan un pensamiento más claro y un enfoque más estable",
    "science.section2.flexibility": "Esta capacidad de cambiar entre combustibles (glucosa cuando está disponible, cetonas cuando los carbohidratos son bajos) se llama flexibilidad metabólica, y es un sello distintivo de un metabolismo más saludable.",
    "science.transport.title": "Visualizando el Transporte de Cetonas",
    "science.transport.1": "Generado en el hígado a partir de ácidos grasos",
    "science.transport.2": "Liberado en el torrente sanguíneo",
    "science.transport.3": "Transportado rápidamente a través de portadores específicos a órganos hambrientos de energía",
    "science.transport.4": "Convertido en ATP dentro de las mitocondrias con una eficiencia impresionante",
    "science.transport.note": "A diferencia de los ácidos grasos de cadena larga, los cuerpos cetónicos no requieren un empaquetado complejo en lipoproteínas; se mueven libremente en la sangre, lo que los convierte en una fuente de energía rápida, limpia y accesible.",
    "science.infographic.title": "Visualizando el Impacto: Insulina Alta vs. Cetonas",
    "science.infographic.desc": "Esta infografía ilustra el \"cambio de combustible\" en el cerebro. Mientras que los niveles altos de insulina pueden crear desechos metabólicos, las cetonas proporcionan una fuente de combustible más limpia y eficiente que penetra fácilmente la barrera hematoencefálica.",
    "science.infographic.high_insulin": "Estado de insulina alta / glucosa alta",
    "science.infographic.high_insulin.1": "Picos y caídas frecuentes de azúcar en sangre",
    "science.infographic.high_insulin.2": "Mayor formación de productos finales de glicación y estrés oxidativo",
    "science.infographic.high_insulin.3": "Posible \"desorden metabólico\": inflamación y función celular deteriorada con el tiempo",
    "science.infographic.ketone_state": "Estado apoyado por cetonas",
    "science.infographic.ketone_state.1": "Insulina más baja y estable",
    "science.infographic.ketone_state.2": "Las cetonas cruzan la barrera hematoencefálica fácilmente y suministran un combustible constante y eficiente",
    "science.infographic.ketone_state.3": "Menos estrés oxidativo por unidad de energía en muchos contextos",
    "science.infographic.ketone_state.4": "Un entorno metabólico más limpio que puede apoyar la salud cerebral a largo plazo",
    "science.section3.title": "Más Que Solo Combustible: Moléculas de Señalización",
    "science.section3.p1": "La investigación moderna muestra que las cetonas no son solo portadores de energía pasivos. Son moléculas de señalización bioactivas que influyen en la inflamación, la expresión génica, las defensas contra el estrés oxidativo y las vías metabólicas involucradas en el envejecimiento y las enfermedades crónicas.",
    "science.card.anti_inflammatory": "Efectos Antiinflamatorios",
    "science.card.anti_inflammatory.subtitle": "BHB y el inflamasoma NLRP3",
    "science.card.anti_inflammatory.desc1": "El inflamasoma NLRP3 es un complejo intracelular que amplifica la inflamación y está implicado en condiciones como la obesidad, la diabetes tipo 2 y las enfermedades cardiovasculares.",
    "science.card.anti_inflammatory.desc2": "BHB inhibe directamente la activación de NLRP3, reduciendo la producción de citocinas inflamatorias como IL-1β e IL-18.",
    "science.card.anti_inflammatory.desc3": "Esta amortiguación de la inflamación crónica de bajo grado puede apoyar vasos sanguíneos más saludables, tejidos metabólicos y potencialmente la función cerebral con el tiempo.",
    "science.card.anti_inflammatory.desc4": "En otras palabras, las cetonas no solo alimentan las células, sino que ayudan a calmar la señalización inflamatoria a nivel molecular.",
    "science.card.epigenetic": "Regulación Epigenética",
    "science.card.epigenetic.subtitle": "BHB como señal epigenética",
    "science.card.epigenetic.desc1": "BHB también actúa como:",
    "science.card.epigenetic.list1": "Un inhibidor de la histona desacetilasa (HDAC)",
    "science.card.epigenetic.list2": "Un donante para la β-hidroxibutirilación de histonas",
    "science.card.epigenetic.desc2": "Estos procesos modifican cuán apretadamente está empaquetado el ADN y cómo se expresan los genes. A través de estos mecanismos epigenéticos, BHB puede:",
    "science.card.epigenetic.list3": "Regular al alza los genes involucrados en la defensa antioxidante y la resistencia al estrés oxidativo",
    "science.card.epigenetic.list4": "Influir en los genes vinculados al metabolismo energético y la función mitocondrial",
    "science.card.epigenetic.list5": "Potencialmente apoyar la longevidad celular y la resiliencia en tejidos como el corazón y el cerebro",
    "science.card.epigenetic.desc3": "Es por eso que los estados cetogénicos se están explorando no solo para trastornos metabólicos, sino también por sus implicaciones protectoras en enfermedades cardiovasculares y neurodegenerativas.",
    "science.references": "Referencias Científicas",

    // Benefits Page
    "benefits.back": "Volver al Inicio",
    "benefits.badge": "Indicaciones y Contraindicaciones",
    "benefits.title": "¿Es Keto Adecuado para Ti?",
    "benefits.subtitle": "Una mirada equilibrada a quién puede beneficiarse más de la dieta cetogénica y quién debe evitarla por razones de seguridad.",
    "benefits.section1.title": "¿Quién Puede Beneficiarse?",
    "benefits.card.obesity": "Obesidad y Síndrome Metabólico",
    "benefits.card.obesity.desc": "Herramienta poderosa para lograr una pérdida de peso clínicamente significativa y mejorar marcadores metabólicos clave.",
    "benefits.card.diabetes": "Diabetes Tipo 2",
    "benefits.card.diabetes.desc": "Las dietas cetogénicas supervisadas pueden conducir a mejoras dramáticas en el control del azúcar en sangre (HbA1c).",
    "benefits.card.nafld": "Hígado Graso (NAFLD)",
    "benefits.card.nafld.desc": "La investigación emergente muestra que las dietas cetogénicas pueden reducir la grasa hepática.",
    "benefits.card.pcos": "SOP (PCOS)",
    "benefits.card.pcos.desc": "Se ha demostrado que mejora el peso, la resistencia a la insulina y la regularidad menstrual en mujeres con SOP.",
    "benefits.section2.title": "Contraindicaciones Absolutas",
    "benefits.contra.warning": "NO comiences una dieta cetogénica si tienes:",
    "benefits.contra.1": "Trastornos conocidos de oxidación de ácidos grasos",
    "benefits.contra.2": "Defectos en el metabolismo de cuerpos cetónicos",
    "benefits.contra.3": "Pancreatitis aguda o crónica severa",
    "benefits.contra.4": "Porfiria o insuficiencia hepática severa",
    "benefits.section3.title": "Contraindicaciones Relativas",
    "benefits.caution": "Estas condiciones requieren supervisión médica experimentada:",
    "benefits.caution.1": "Diabetes Tipo 1",
    "benefits.caution.2": "Enfermedad Renal Crónica",
    "benefits.caution.3": "Embarazo y Lactancia",
    "benefits.caution.4": "Historial de Trastornos Alimenticios",
    "benefits.caution.5": "Dislipidemia No Controlada",
    "benefits.bottomline.title": "La Conclusión",
    "benefits.bottomline.desc": "Para personas con obesidad y resistencia a la insulina, la dieta cetogénica puede ser una herramienta altamente efectiva, pero es crucial consultar con un profesional de la salud.",

    // Guide Page
    "guide.back": "Volver al Inicio",
    "guide.badge": "Aplicación Práctica",
    "guide.title": "Comenzando con Keto: Las Primeras Dos Semanas",
    "guide.subtitle": "Una guía paso a paso para navegar la fase de inducción, manejar efectos secundarios y prepararte para el éxito.",
    "guide.step1.title": "Preparación Médica",
    "guide.step1.desc": "Antes de embarcarse en una dieta cetogénica, es mejor práctica:",
    "guide.step1.meds": "Revisar Medicamentos",
    "guide.step1.meds.desc": "Discute con tu médico, especialmente para medicamentos de diabetes y presión arterial.",
    "guide.step1.labs": "Análisis de Laboratorio Base",
    "guide.step1.labs.desc": "Glucosa en ayunas, HbA1c, panel de lípidos, enzimas hepáticas y función renal.",
    "guide.step2.title": "La Fase de Inducción (Días 1-14)",
    "guide.step2.expect": "Qué Esperar",
    "guide.step2.expect.desc": "Durante los primeros 3-14 días, tu cuerpo hace la transición a la cetosis. Probablemente experimentarás una rápida pérdida de peso de agua.",
    "guide.step2.flu": "La \"Gripe Keto\"",
    "guide.step2.flu.desc": "Síntomas transitorios como dolor de cabeza, fatiga y niebla mental son comunes pero temporales.",
    "guide.step3.title": "Manejo de Efectos Secundarios",
    "guide.step3.hydrate": "Mantente Hidratado",
    "guide.step3.hydrate.desc": "Bebe mucha agua para reemplazar los fluidos perdidos.",
    "guide.step3.electrolytes": "Electrolitos",
    "guide.step3.electrolytes.desc": "Suplementa sodio, potasio y magnesio.",
    "guide.step3.ease": "Ve Despacio",
    "guide.step3.ease.desc": "Reduce gradualmente los carbohidratos si los síntomas son severos.",
    "guide.longterm.title": "Éxito a Largo Plazo y Trampas",
    "guide.longterm.p1": "El mayor desafío es la sostenibilidad. Para tener éxito a largo plazo, encuentra tu \"por qué\" y planifica las comidas.",
    "guide.longterm.p2": "Cuidado con: Deficiencias de nutrientes, cálculos renales y colesterol LDL elevado."
  },
  cn: {
    // Navigation
    "nav.home": "首页",
    "nav.science": "科学原理",
    "nav.benefits": "益处与风险",
    "nav.guide": "入门指南",
    "nav.getStarted": "立即开始",
    
    // Home
    "home.badge": "科学循证营养",
    "home.title": "解锁代谢健康：生酮饮食终极指南",
    "home.subtitle": "科学探索生酮饮食如何改变您的新陈代谢——从细胞内的分子机制到减肥、2型糖尿病、脂肪肝和代谢综合征的实际应用。",
    "home.subtitle2": "了解如何安全地从依赖糖分转变为燃烧脂肪，提高胰岛素敏感性，并通过基于证据的生酮策略支持长期健康。",
    "home.cta.start": "开启您的旅程",
    "home.cta.science": "探索科学原理",
    "home.card.metabolic": "代谢转换",
    "home.card.metabolic.desc": "从葡萄糖代谢转向脂肪代谢，获得持久能量。",
    "home.benefits.title": "不仅仅是减肥",
    "home.benefits.subtitle": "现代研究表明，酮体不仅是燃料，更是调节关键细胞过程的强大信号分子。",
    "home.card.cognitive": "认知功能",
    "home.card.neuroprotection": "神经保护",
    "home.card.neuroprotection.desc": "酮体为大脑提供稳定的燃料来源，减少对葡萄糖的依赖，并可能提供神经保护作用。",
    "home.card.metabolic_health": "代谢健康",
    "home.card.inflammation": "炎症控制",
    "home.card.inflammation.desc": "BHB直接抑制NLRP3炎症小体（慢性炎症的关键驱动因素），促进更好的长期健康。",
    "home.card.cardio": "心血管健康",
    "home.card.weight": "体重管理",
    "home.card.weight.desc": "卓越的食欲控制和脂肪动员使生酮成为可持续减肥和逆转代谢综合征的有力工具。",
    "home.how.title": "生酮饮食如何运作",
    "home.how.desc": "在标准西方饮食中，大多数细胞主要依靠葡萄糖运行。生酮饮食从根本上改变了这种代谢范式。通过限制碳水化合物摄入并增加健康脂肪，身体进入酮症状态。",
    "home.how.fuel": "高效燃料",
    "home.how.fuel.desc": "酮体是水溶性的，易于输送到大脑和肌肉，提供清洁燃烧的能源。",
    "home.how.hormones": "荷尔蒙平衡",
    "home.how.hormones.desc": "较低的胰岛素水平释放储存的脂肪用于能量，并随着时间的推移改善胰岛素敏感性。",
    "home.how.deepdive": "阅读分子深度解析",
    "home.cta.transform": "准备好改变您的健康了吗？",
    "home.cta.transform.desc": "获取安全开始生酮、管理副作用和实现长期成功的完整指南。",
    "home.cta.check": "查看适应症",

    // Footer
    "footer.desc": "一个全面、科学支持的资源，用于安全有效地理解和实施生酮饮食。",
    "footer.content": "内容",
    "footer.legal": "法律",
    "footer.privacy": "隐私政策",
    "footer.terms": "服务条款",
    "footer.disclaimer": "医疗免责声明",
    "footer.language": "语言",
    "footer.rights": "KetoGuide. 版权所有. 信息仅供教育目的。",

    // Science Page
    "science.back": "返回首页",
    "science.badge": "分子机制",
    "science.title": "生酮饮食如何运作：分子深度解析",
    "science.subtitle": "了解从葡萄糖到脂肪代谢的代谢转变以及酮体的信号传递能力。",
    "science.section1.title": "从葡萄糖到脂肪代谢",
    "science.section1.p1": "在典型的西方饮食中，我们的细胞主要依靠葡萄糖运行。进食富含碳水化合物的一餐后，血糖升高，促使胰腺释放胰岛素。胰岛素帮助细胞吸收葡萄糖并将其作为糖原和脂肪储存多余能量，同时抑制脂肪组织中的脂肪分解。",
    "science.section1.p2": "生酮饮食从根本上改变了这种范式。通过将碳水化合物摄入量限制在每天 < 50 克（通常占总能量的 5–10%）并将脂肪摄入量增加到约 70–80%，您可以降低胰岛素并迫使身体寻找替代燃料。几天后，这会驱动肝脏进行生酮作用，产生酮体并启动营养性酮症。",
    "science.card.triggers": "代谢转变触发因素",
    "science.card.triggers.desc": "一旦限制碳水化合物且胰岛素下降，一系列代谢事件就开始了：",
    "science.card.insulin": "低胰岛素",
    "science.card.insulin.desc1": "血糖和胰岛素水平显著下降。",
    "science.card.insulin.desc2": "低胰岛素消除了脂肪分解的“刹车”。",
    "science.card.insulin.desc3": "细胞随着时间的推移对胰岛素变得更加敏感，从而改善代谢健康。",
    "science.card.fat": "脂肪分解（脂解）",
    "science.card.fat.desc1": "在脂肪组织中，激素敏感性脂肪酶 (HSL) 被激活。",
    "science.card.fat.desc2": "HSL 将储存的甘油三酯分解为游离脂肪酸 (FFA) 和甘油。",
    "science.card.fat.desc3": "FFA 通过血液输送到肝脏和其他组织，作为主要的燃料来源。",
    "science.card.ketone": "酮体产生（生酮作用）",
    "science.card.ketone.desc1": "在肝细胞的线粒体内，游离脂肪酸进行 β-氧化，生成乙酰辅酶 A。",
    "science.card.ketone.desc2": "过量的乙酰辅酶 A 进入生酮作用，产生酮体：β-羟基丁酸 (BHB)、乙酰乙酸 (AcAc) 和丙酮。",
    "science.card.ketone.desc3": "这些酮体随后被释放到血液中，成为大脑、心脏和肌肉的核心燃料。",
    "science.card.note": "营养性酮症 (BHB ~0.5–3.0 mmol/L) 与糖尿病酮症酸中毒不同。在营养性酮症中，pH 值保持正常，胰岛素水平低但存在，并且该过程受到严格调节。",
    "science.section2.title": "酮体作为优质燃料来源",
    "science.section2.p1": "酮体是水溶性的，这意味着它们很容易通过血液输送并穿过细胞膜。肌肉、心脏和大脑中的细胞表达转运蛋白 (MCT)，可以快速摄取酮体。在细胞内，酮体被转化回乙酰辅酶 A 并进入克雷布斯循环 (TCA 循环) 以产生 ATP——细胞的通用能量货币。",
    "science.section2.subtitle": "高效的大脑燃料与代谢灵活性",
    "science.section2.p2": "酮症的一个关键优势是，大脑可以从酮体中获得很大一部分能量，减少对葡萄糖的依赖。这：",
    "science.section2.list1": "平滑血糖波动",
    "science.section2.list2": "可以减少与高碳水化合物饮食相关的“能量崩溃”",
    "science.section2.list3": "有助于解释为什么许多处于酮症状态的人报告思维更清晰、注意力更稳定",
    "science.section2.flexibility": "这种在燃料之间切换的能力——有葡萄糖时用葡萄糖，碳水化合物低时用酮体——被称为代谢灵活性，这是更健康代谢的标志。",
    "science.transport.title": "可视化酮体运输",
    "science.transport.1": "在肝脏中由脂肪酸生成",
    "science.transport.2": "释放到血液中",
    "science.transport.3": "通过特定载体快速输送到能量饥渴的器官",
    "science.transport.4": "在线粒体内以惊人的效率转化为 ATP",
    "science.transport.note": "与长链脂肪酸不同，酮体不需要在脂蛋白中进行复杂的包装；它们在血液中自由移动，使其成为一种快速、清洁且易于获取的能量来源。",
    "science.infographic.title": "可视化影响：高胰岛素与酮体",
    "science.infographic.desc": "这张信息图展示了大脑中的“燃料转换”。虽然高胰岛素水平会产生代谢碎片，但酮体提供了一种更清洁、更高效的燃料来源，可以轻松穿透血脑屏障。",
    "science.infographic.high_insulin": "高胰岛素/高葡萄糖状态",
    "science.infographic.high_insulin.1": "频繁的血糖飙升和崩溃",
    "science.infographic.high_insulin.2": "更多糖基化终产物的形成和氧化应激",
    "science.infographic.high_insulin.3": "潜在的“代谢混乱”——随着时间的推移导致炎症和细胞功能受损",
    "science.infographic.ketone_state": "酮体支持状态",
    "science.infographic.ketone_state.1": "更低且更稳定的胰岛素",
    "science.infographic.ketone_state.2": "酮体容易穿过血脑屏障并提供稳定、高效的燃料",
    "science.infographic.ketone_state.3": "在许多情况下，每单位能量产生的氧化应激更少",
    "science.infographic.ketone_state.4": "更清洁的代谢环境，可能支持长期大脑健康",
    "science.section3.title": "不仅仅是燃料：信号分子",
    "science.section3.p1": "现代研究表明，酮体不仅仅是被动的能量载体。它们是具有生物活性的信号分子，影响炎症、基因表达、氧化应激防御以及涉及衰老和慢性疾病的代谢途径。",
    "science.card.anti_inflammatory": "抗炎作用",
    "science.card.anti_inflammatory.subtitle": "BHB 与 NLRP3 炎症小体",
    "science.card.anti_inflammatory.desc1": "NLRP3 炎症小体是一种细胞内复合物，会放大炎症，并与肥胖、2 型糖尿病和心血管疾病等疾病有关。",
    "science.card.anti_inflammatory.desc2": "BHB 直接抑制 NLRP3 激活，减少炎症细胞因子如 IL-1β 和 IL-18 的产生。",
    "science.card.anti_inflammatory.desc3": "这种对慢性低度炎症的抑制可以支持更健康的血管、代谢组织，并随着时间的推移可能支持大脑功能。",
    "science.card.anti_inflammatory.desc4": "换句话说，酮体不仅仅为细胞提供燃料——它们有助于在分子水平上平息炎症信号。",
    "science.card.epigenetic": "表观遗传调节",
    "science.card.epigenetic.subtitle": "BHB 作为表观遗传信号",
    "science.card.epigenetic.desc1": "BHB 还充当：",
    "science.card.epigenetic.list1": "组蛋白去乙酰化酶 (HDAC) 抑制剂",
    "science.card.epigenetic.list2": "组蛋白 β-羟基丁酰化的供体",
    "science.card.epigenetic.desc2": "这些过程改变了 DNA 包装的紧密程度以及基因的表达方式。通过这些表观遗传机制，BHB 可以：",
    "science.card.epigenetic.list3": "上调涉及抗氧化防御和氧化应激抵抗的基因",
    "science.card.epigenetic.list4": "影响与能量代谢和线粒体功能相关的基因",
    "science.card.epigenetic.list5": "可能支持心脏和大脑等组织的细胞寿命和恢复力",
    "science.card.epigenetic.desc3": "这就是为什么生酮状态不仅被探索用于代谢紊乱，还被探索用于其在心血管和神经退行性疾病中的保护意义。",
    "science.references": "科学参考文献",

    // Benefits Page
    "benefits.back": "返回首页",
    "benefits.badge": "适应症与禁忌症",
    "benefits.title": "生酮适合您吗？",
    "benefits.subtitle": "平衡地看待谁能从生酮饮食中获益最多，以及谁出于安全原因应该避免。",
    "benefits.section1.title": "谁能获益？",
    "benefits.card.obesity": "肥胖与代谢综合征",
    "benefits.card.obesity.desc": "实现临床意义上的减肥和改善关键代谢指标（如腰围、甘油三酯、HDL胆固醇和血压）的有力工具。",
    "benefits.card.diabetes": "2型糖尿病",
    "benefits.card.diabetes.desc": "受监督的生酮饮食可以显著改善血糖控制（HbA1c），降低空腹血糖，并通常允许减少药物。",
    "benefits.card.nafld": "非酒精性脂肪肝",
    "benefits.card.nafld.desc": "新兴研究表明，生酮饮食可以减少肝脏脂肪并降低肝酶。",
    "benefits.card.pcos": "多囊卵巢综合征",
    "benefits.card.pcos.desc": "已被证明可以改善多囊卵巢综合征女性的体重、胰岛素抵抗、雄激素水平和月经规律。",
    "benefits.section2.title": "绝对禁忌症",
    "benefits.contra.warning": "如果您有以下情况，请勿开始生酮饮食：",
    "benefits.contra.1": "已知的脂肪酸氧化障碍（如CPT-II缺乏症）",
    "benefits.contra.2": "酮体代谢缺陷",
    "benefits.contra.3": "急性或严重慢性胰腺炎",
    "benefits.contra.4": "卟啉症或严重肝衰竭",
    "benefits.section3.title": "相对禁忌症",
    "benefits.caution": "这些情况需要在饮食前和饮食期间进行经验丰富的医疗监督：",
    "benefits.caution.1": "1型糖尿病",
    "benefits.caution.2": "慢性肾脏病",
    "benefits.caution.3": "怀孕和哺乳期",
    "benefits.caution.4": "饮食失调史",
    "benefits.caution.5": "未控制的血脂异常",
    "benefits.bottomline.title": "底线",
    "benefits.bottomline.desc": "对于肥胖和胰岛素抵抗的人来说，生酮饮食可能是一个非常有效的工具，但在开始之前咨询医疗专业人员至关重要。",

    // Guide Page
    "guide.back": "返回首页",
    "guide.badge": "实际应用",
    "guide.title": "开始生酮：前两周",
    "guide.subtitle": "导航诱导期、管理副作用并为长期成功做好准备的分步指南。",
    "guide.step1.title": "医疗准备",
    "guide.step1.desc": "在开始生酮饮食之前，最佳做法是：",
    "guide.step1.meds": "审查药物",
    "guide.step1.meds.desc": "与您的医生讨论，特别是糖尿病和血压药物。",
    "guide.step1.labs": "基线实验室检查",
    "guide.step1.labs.desc": "空腹血糖、HbA1c、血脂面板、肝酶和肾功能。",
    "guide.step2.title": "诱导期（第1-14天）",
    "guide.step2.expect": "预期情况",
    "guide.step2.expect.desc": "在最初的3-14天内，您的身体过渡到酮症。随着糖原储存耗尽，您可能会经历快速的水分重量减轻。",
    "guide.step2.flu": "“生酮流感”",
    "guide.step2.flu.desc": "头痛、疲劳、脑雾和恶心等短暂症状很常见，但只是暂时的。",
    "guide.step3.title": "管理副作用",
    "guide.step3.hydrate": "保持水分",
    "guide.step3.hydrate.desc": "多喝水以补充流失的体液。",
    "guide.step3.electrolytes": "电解质",
    "guide.step3.electrolytes.desc": "补充钠、钾和镁。",
    "guide.step3.ease": "循序渐进",
    "guide.step3.ease.desc": "如果症状严重，逐渐减少碳水化合物。",
    "guide.longterm.title": "长期成功与陷阱",
    "guide.longterm.p1": "最大的挑战是可持续性。为了长期成功，找到您的“为什么”，提前计划膳食，并加入支持社区。",
    "guide.longterm.p2": "注意：营养缺乏（吃蔬菜！）、肾结石（保持水分！）和LDL胆固醇升高（与医生一起监测）。"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
