import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es' | 'cn' | 'sk';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.science": "The Science",
    "nav.benefits": "Benefits & Risks",
    "nav.guide": "Start Guide",
    "nav.getStarted": "Get Started",
    
    // Home
    "home.badge": "Science-Backed Nutrition",
    "home.title": "Unlock Metabolic Health: The Definitive Keto Guide",
    "home.subtitle": "A science-driven exploration of how the ketogenic diet can transform your metabolism — from molecular mechanisms inside your cells to real-world application for weight loss, type 2 diabetes, fatty liver, and metabolic syndrome.",
    "home.subtitle2": "Learn how to safely switch from sugar-dependence to fat-burning, improve insulin sensitivity, and support long-term health with evidence-based ketogenic strategies.",
    "home.cta.start": "Start Your Journey",
    "home.cta.science": "Explore the Science",
    "home.card.metabolic": "Metabolic Switch",
    "home.card.metabolic.desc": "Shift from glucose to fat metabolism for sustained energy.",
    "home.benefits.title": "More Than Just Weight Loss",
    "home.benefits.subtitle": "Modern research reveals that ketones are powerful signaling molecules that regulate critical cellular processes.",
    "home.card.cognitive": "Cognitive Function",
    "home.card.neuroprotection": "Neuroprotection",
    "home.card.neuroprotection.desc": "The brain's energy problem: Your brain is small in size but huge in energy demand, using about 20% of your resting energy even though it's only ~2% of your body weight. Under a typical high-carb diet, that energy comes primarily from glucose. When glucose supply is unstable (skipped meals, blood sugar swings, insulin resistance), many people feel brain fog, irritability, and crashes in focus and mood. Nutritional ketosis offers the brain a second fuel line: ketone bodies. These are small, water-soluble molecules produced by the liver when carbohydrate intake is low and fat oxidation is high. In ketosis, blood levels of BHB and acetoacetate rise into the 0.5–3.0 mmol/L range (nutritional, not diabetic ketosis). These ketones cross the blood–brain barrier via monocarboxylate transporters, are converted to acetyl-CoA inside neurons, and enter the Krebs cycle to generate ATP – the cell's main energy currency. Recent reviews show that ketones can enhance brain energy metabolism, improve mitochondrial efficiency, and increase antioxidant capacity in neural tissue. Practically, people often report more stable mental energy, fewer energy \"crashes,\" and better ability to focus for longer periods. Beyond everyday focus, ketogenic diets are being studied for their impact on neurological diseases – where brain energy metabolism and inflammation play central roles. Recent clinical and preclinical work suggests that ketogenic interventions can improve aspects of motor and cognitive function in neurodegenerative conditions such as Parkinson's disease, reduce seizure frequency and improve developmental outcomes in refractory epilepsy and GLUT1 deficiency, and potentially support cognition in Alzheimer's disease and other dementias. Ketones support brain health through several interconnected pathways: mitochondrial support (enhancing efficiency, reducing dysfunction, lowering ROS production), neurotransmitter balance (influencing GABA/glutamate balance), epigenetic and signaling effects (BHB acts as an HDAC inhibitor, upregulating genes involved in antioxidant defense), and reduced neuroinflammation (by dampening inflammatory pathways, especially NLRP3). Ketones are not just an \"emergency backup fuel\" – they are an optimized fuel and signaling system that can support brain function, especially when glucose metabolism is impaired.",
    "home.card.metabolic_health": "Metabolic Health",
    "home.card.inflammation": "Inflammation Control",
    "home.card.inflammation.desc": "Chronic inflammation: the hidden driver of metabolic disease. Obesity, type 2 diabetes, fatty liver, and cardiovascular disease share a common thread: chronic low-grade inflammation. This persistent inflammatory state disrupts insulin signaling, damages blood vessels, and accelerates tissue aging and organ dysfunction. A major molecular player in this process is the NLRP3 inflammasome – a multi-protein complex inside immune cells (like macrophages and microglia) that activates inflammatory cytokines such as IL-1β and IL-18. Overactivation of NLRP3 is implicated in obesity-related insulin resistance, atherosclerosis, neurodegenerative diseases, and inflammatory bowel disease. One of the most fascinating findings in ketone research: β-hydroxybutyrate directly inhibits NLRP3 inflammasome activation. Multiple lines of evidence show that BHB reduces NLRP3 activation and downstream IL-1β/IL-18 secretion in immune cells, dampens microglial activation and neuroinflammation in brain models, and mitigates inflammatory damage in models of Alzheimer's disease and other conditions. A 2023–2025 wave of studies confirms that fasting and ketogenic interventions that raise BHB levels are associated with reduced NLRP3 activity and lower inflammatory cytokine output in both animal and human systems. Experimental work infusing BHB in rodents shows antidepressant-like and anti-inflammatory effects, again tied to NLRP3 modulation. In short, when you're in nutritional ketosis, your circulating BHB is not only feeding tissues – it's also acting as an endogenous anti-inflammatory signal. The BHB–NLRP3 link has consequences across the body: in the liver, reduced inflammasome activation may help limit progression from simple fatty liver to more inflamed, fibrotic stages; in adipose tissue, lower inflammatory signaling can improve insulin sensitivity; in the vasculature, decreased IL-1β/IL-18 and oxidative stress can support healthier endothelial function. Because chronic inflammation and insulin resistance are tightly linked, reducing inflammatory activity via ketones can translate into better insulin sensitivity, lower fasting glucose and HbA1c, improvements in liver enzymes and hepatic fat content, and more favorable cardiometabolic risk profiles. Recent umbrella and systematic reviews (2023–2025) conclude that ketogenic diets are effective for improving weight, glycaemic control, and several metabolic risk factors, and that anti-inflammatory effects are a plausible mechanistic link behind these improvements. By elevating BHB, a ketogenic diet doesn't just \"change macros\" – it engages an internal anti-inflammatory circuit that targets one of the core molecular drivers of metabolic disease.",
    "home.card.cardio": "Cardiovascular",
    "home.card.weight": "Weight Management",
    "home.card.weight.desc": "Why weight loss is biologically hard – and where keto helps: Most diets fail not because people are weak, but because the body fights weight loss. As you lose weight, ghrelin (hunger hormone) tends to rise, satiety signals can become less effective, and metabolic rate may decrease, making it easier to regain weight. This is where nutritional ketosis has a unique advantage, especially in people with overweight or obesity. A series of studies and reviews show that ketogenic diets prevent or blunt the typical rise in ghrelin seen with weight loss, reduce subjective hunger and food cravings, and often lead to spontaneous calorie reduction without strict portion control. In other words, many people simply aren't as hungry on keto, which makes it more realistic to maintain a calorie deficit long enough to lose significant weight. On a standard diet, high insulin keeps a tight lock on fat stores. Keto lowers insulin and improves insulin sensitivity, which unlocks stored fat from adipose tissue, increases fat oxidation in muscle and liver, and trains metabolism to be more flexible, switching between fat and ketones rather than relying almost exclusively on glucose. This shift is particularly powerful for people with metabolic syndrome, where insulin resistance and visceral fat are central problems. Ketogenic diets have been shown to produce greater reductions in body weight, BMI, and waist circumference than higher-carb comparators in many trials. Recent meta-analyses (2023–2025) of randomized controlled trials report that low-carb ketogenic diets significantly reduce body weight and body fat percentage, improve fasting glucose, HbA1c, and insulin resistance markers, and often outperform low-fat or higher-carb diets in the first 3–12 months, especially at carb intakes ≤50 g/day. Weight loss alone helps cardiovascular health, but ketogenic diets also alter key risk markers: triglycerides often drop substantially, HDL (\"good\") cholesterol usually increases, and blood pressure tends to decrease, partly thanks to weight loss and lower insulin. The LDL story is more complex: on average, many studies show modest or no change in LDL-C on well-designed keto diets, especially those rich in unsaturated fats. However, a subset of individuals – sometimes called \"lean mass hyper-responders\" – experience marked increases in LDL-C and apoB on high-saturated-fat keto diets. For this reason, cardiometabolic experts recommend emphasizing olive oil, avocado, nuts, seeds, and fatty fish over large amounts of butter, cream, and processed meats, and regular lipid monitoring for anyone using keto as a long-term strategy. For individuals with metabolic syndrome (abdominal obesity, high BP, high triglycerides, low HDL, impaired glucose), a ketogenic diet can rapidly reduce waist circumference, improve blood pressure, triglycerides, HDL, and glycaemic control, reduce liver fat and improve liver enzymes in MASLD/NAFLD, and provide a powerful \"reset\" that makes it easier to transition later into a more moderate, sustainable pattern. Meta-analyses up to 2025 generally support KD as an effective short- to medium-term strategy for weight loss and metabolic risk reduction, especially when professionally supervised and combined with lifestyle changes (sleep, stress, strength training).",
    "home.how.title": "How the Ketogenic Diet Works",
    "home.how.desc": "In a standard Western diet, most cells run primarily on glucose. The ketogenic diet fundamentally shifts this metabolic paradigm. By restricting carbohydrate intake and increasing healthy fats, the body enters a state of ketosis.",
    "home.how.fuel": "Efficient Fuel",
    "home.how.fuel.desc": "Ketones are water-soluble and easily transported to the brain and muscles, providing a clean-burning energy source.",
    "home.how.hormones": "Hormonal Balance",
    "home.how.hormones.desc": "Lower insulin levels unlock stored fat for energy and improve insulin sensitivity over time.",
    "home.how.deepdive": "Read the Molecular Deep Dive",
    "home.cta.transform": "Ready to Transform Your Health?",
    "home.cta.transform.desc": "Get the complete guide to starting keto safely, managing side effects, and achieving long-term success.",
    "home.cta.check": "Check Indications",

    // Footer
    "footer.desc": "A comprehensive, science-backed resource for understanding and implementing the ketogenic diet safely and effectively.",
    "footer.content": "Content",
    "footer.legal": "Legal",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.disclaimer": "Medical Disclaimer",
    "footer.language": "Language",
    "footer.rights": "KetoMindset. All rights reserved. Information is for educational purposes only.",
    
    // Science Page
    "science.back": "Back to Home",
    "science.badge": "Molecular Mechanisms",
    "science.title": "How the Ketogenic Diet Works: A Molecular Deep Dive",
    "science.subtitle": "Understanding the metabolic shift from glucose to fat metabolism and the signaling power of ketone bodies.",
    "science.section1.title": "From Glucose to Fat Metabolism",
    "science.section1.p1": "In a typical Western diet, our cells primarily run on glucose. After a carbohydrate-rich meal, blood glucose rises, prompting the pancreas to release insulin. Insulin helps cells absorb glucose and store excess energy as glycogen and fat, while suppressing fat breakdown in adipose tissue.",
    "science.section1.p2": "The ketogenic diet fundamentally shifts this paradigm. By restricting carbohydrate intake to < 50 grams per day (typically 5–10% of total energy) and increasing fat intake to about 70–80% of calories, you lower insulin and force the body to seek an alternative fuel. Over several days, this drives the liver into ketogenesis, producing ketone bodies and initiating nutritional ketosis.",
    "science.card.triggers": "The Metabolic Shift Triggers",
    "science.card.triggers.desc": "Once carbohydrates are restricted and insulin falls, a cascade of metabolic events begins:",
    "science.card.insulin": "Lower Insulin",
    "science.card.insulin.desc1": "Blood glucose and insulin levels drop significantly.",
    "science.card.insulin.desc2": "Low insulin removes the \"brake\" on fat breakdown.",
    "science.card.insulin.desc3": "Cells become more sensitive to insulin over time, improving metabolic health.",
    "science.card.fat": "Fat Breakdown (Lipolysis)",
    "science.card.fat.desc1": "In adipose tissue, hormone-sensitive lipase (HSL) is activated.",
    "science.card.fat.desc2": "HSL breaks down stored triglycerides into free fatty acids (FFA) and glycerol.",
    "science.card.fat.desc3": "FFA travel through the bloodstream to the liver and other tissues as a major fuel source.",
    "science.card.ketone": "Ketone Production (Ketogenesis)",
    "science.card.ketone.desc1": "Inside the mitochondria of liver cells, free fatty acids undergo β-oxidation, generating acetyl-CoA.",
    "science.card.ketone.desc2": "Excess acetyl-CoA is routed into ketogenesis, producing ketone bodies: β-hydroxybutyrate (BHB), Acetoacetate (AcAc), and Acetone.",
    "science.card.ketone.desc3": "These ketones are then released into the bloodstream and become a central fuel for the brain, heart, and muscles.",
    "science.card.note": "Nutritional ketosis (BHB ~0.5–3.0 mmol/L) is not the same as diabetic ketoacidosis. In nutritional ketosis, pH remains normal, insulin is low but present, and the process is tightly regulated.",
    "science.section2.title": "Ketones as a Superior Fuel Source",
    "science.section2.p1": "Ketone bodies are water-soluble, which means they travel easily through the bloodstream and across cell membranes. Cells in muscle, heart, and brain express transporters (MCTs) that rapidly take up ketones. Inside the cell, ketones are converted back to acetyl-CoA and enter the Krebs cycle (TCA cycle) to produce ATP – the universal energy currency of the cell.",
    "science.section2.subtitle": "Efficient Brain Fuel & Metabolic Flexibility",
    "science.section2.p2": "A key advantage of ketosis is that the brain can obtain a significant share of its energy from ketones, reducing its reliance on glucose. This:",
    "science.section2.list1": "Smooths out blood sugar fluctuations",
    "science.section2.list2": "Can reduce \"energy crashes\" associated with high-carb eating",
    "science.section2.list3": "Helps explain why many people in ketosis report clearer thinking and more stable focus",
    "science.section2.flexibility": "This ability to switch between fuels — glucose when available, ketones when carbs are low — is called metabolic flexibility, and it’s a hallmark of a healthier metabolism.",
    "science.transport.title": "Visualizing Ketone Transport",
    "science.transport.1": "Generated in the liver from fatty acids",
    "science.transport.2": "Released into the bloodstream",
    "science.transport.3": "Rapidly transported via specific carriers to energy-hungry organs",
    "science.transport.4": "Converted to ATP inside mitochondria with impressive efficiency",
    "science.transport.note": "Unlike long-chain fatty acids, ketone bodies don’t require complex packaging in lipoproteins; they move freely in blood, making them a fast, clean, and accessible energy source.",
    "science.infographic.title": "Why Keto Works for Weight Loss (Especially in Obesity)",
    "science.infographic.desc": "This infographic breaks down the scientific mechanisms by which ketogenic diets contribute to weight loss and metabolic improvements. It explains four key pathways: appetite suppression through hunger hormone regulation, increased energy expenditure, insulin reduction and fat mobilization, and the magnitude of weight loss outcomes. Based on meta-analyses and randomized controlled trials (2024-2025), ketogenic diets produce superior weight loss in obesity through multiple complementary mechanisms, with best results achieved when combined with adequate protein intake and resistance training.",
    "science.section3.title": "More Than Just Fuel: Signaling Molecules",
    "science.section3.p1": "Modern research shows that ketones are not just passive energy carriers. They are bioactive signaling molecules that influence inflammation, gene expression, oxidative stress defenses, and metabolic pathways involved in aging and chronic disease.",
    "science.card.anti_inflammatory": "Anti-Inflammatory Effects",
    "science.card.anti_inflammatory.subtitle": "BHB and the NLRP3 inflammasome",
    "science.card.anti_inflammatory.desc1": "The NLRP3 inflammasome is an intracellular complex that amplifies inflammation and is implicated in conditions like obesity, type 2 diabetes, and cardiovascular disease.",
    "science.card.anti_inflammatory.desc2": "BHB directly inhibits NLRP3 activation, reducing production of inflammatory cytokines such as IL-1β and IL-18.",
    "science.card.anti_inflammatory.desc3": "This dampening of chronic, low-grade inflammation can support healthier blood vessels, metabolic tissues, and potentially brain function over time.",
    "science.card.anti_inflammatory.desc4": "In other words, ketones don’t just fuel cells — they help calm down inflammatory signaling at the molecular level.",
    "science.card.epigenetic": "Epigenetic Regulation",
    "science.card.epigenetic.subtitle": "BHB as an epigenetic signal",
    "science.card.epigenetic.desc1": "BHB also acts as:",
    "science.card.epigenetic.list1": "A histone deacetylase (HDAC) inhibitor",
    "science.card.epigenetic.list2": "A donor for histone β-hydroxybutyrylation",
    "science.card.epigenetic.desc2": "These processes modify how tightly DNA is packaged and how genes are expressed. Through these epigenetic mechanisms, BHB can:",
    "science.card.epigenetic.list3": "Upregulate genes involved in antioxidant defense and oxidative stress resistance",
    "science.card.epigenetic.list4": "Influence genes tied to energy metabolism and mitochondrial function",
    "science.card.epigenetic.list5": "Potentially support cellular longevity and resilience in tissues like the heart and brain",
    "science.card.epigenetic.desc3": "This is why ketogenic states are being explored not only for metabolic disorders, but also for their protective implications in cardiovascular and neurodegenerative diseases.",
    "science.references": "Scientific References",

    // Benefits Page
    "benefits.back": "Back to Home",
    "benefits.badge": "Indications & Contraindications",
    "benefits.title": "Is Keto Right for You?",
    "benefits.subtitle": "A balanced, science-informed look at who can benefit most from a ketogenic diet — and who should avoid it or use it only under close medical supervision.",
    "benefits.intro": "The ketogenic diet is not a one-size-fits-all solution. For some people, especially those with obesity and insulin resistance, it can be a powerful therapeutic tool. For others, it may be ineffective, difficult to sustain, or even unsafe.",
    "benefits.section1.title": "Who Can Benefit?",
    "benefits.card.obesity": "Obesity & Metabolic Syndrome",
    "benefits.card.obesity.desc": "For individuals with overweight or obesity, especially those with metabolic syndrome, ketogenic diets consistently produce clinically meaningful weight loss, often greater than standard low-fat diets over the short to medium term.",
    "benefits.card.obesity.improvements": "Common improvements include:",
    "benefits.card.obesity.list1": "Lower waist circumference",
    "benefits.card.obesity.list2": "Lower triglycerides",
    "benefits.card.obesity.list3": "Higher HDL ('good') cholesterol",
    "benefits.card.obesity.list4": "Modest reductions in blood pressure",
    "benefits.card.diabetes": "Type 2 Diabetes",
    "benefits.card.diabetes.desc": "For people with type 2 diabetes (T2D), carbohydrate restriction goes straight to the root problem: impaired glucose and insulin regulation.",
    "benefits.card.diabetes.list1": "Significantly reduce HbA1c",
    "benefits.card.diabetes.list2": "Lower fasting glucose and insulin",
    "benefits.card.diabetes.list3": "Improve insulin sensitivity",
    "benefits.card.diabetes.list4": "Allow many patients to reduce or discontinue medications",
    "benefits.card.diabetes.warning": "Self-directed keto without professional support is risky for people on glucose-lowering drugs.",
    "benefits.card.nafld": "NAFLD / MASLD",
    "benefits.card.nafld.desc": "Emerging evidence suggests that ketogenic diets can reduce liver fat content, lower liver enzymes, and improve overall metabolic risk markers.",
    "benefits.card.nafld.list1": "Reduce liver fat content",
    "benefits.card.nafld.list2": "Lower liver enzymes (ALT, AST, GGT)",
    "benefits.card.nafld.list3": "Decrease de novo lipogenesis",
    "benefits.card.pcos": "PCOS",
    "benefits.card.pcos.desc": "In women with PCOS and overweight/obesity, ketogenic diets can promote weight loss, improve insulin resistance, and reduce androgen levels.",
    "benefits.card.pcos.list1": "Promote weight loss",
    "benefits.card.pcos.list2": "Improve insulin resistance",
    "benefits.card.pcos.list3": "Enhance menstrual regularity",
    "benefits.section2.title": "Absolute Contraindications",
    "benefits.contra.warning": "Do NOT start a ketogenic diet without specialist guidance if you have any of the following:",
    "benefits.contra.group1": "Metabolic Disorders",
    "benefits.contra.1": "Known disorders of fatty acid oxidation (e.g., CPT-II deficiency)",
    "benefits.contra.2": "Defects in ketone body metabolism",
    "benefits.contra.group2": "Organ Failure",
    "benefits.contra.3": "Acute or severe chronic pancreatitis",
    "benefits.contra.4": "Porphyria or severe liver failure",
    "benefits.contra.note": "These conditions are rare but can turn a ketogenic diet into a medical emergency.",
    "benefits.section3.title": "Relative Contraindications",
    "benefits.caution": "These situations don't automatically rule out keto, but they demand experienced medical supervision:",
    "benefits.caution.1": "Type 1 Diabetes",
    "benefits.caution.1.desc": "Aggressive carb restriction combined with insufficient insulin can trigger diabetic ketoacidosis (DKA).",
    "benefits.caution.1.note": "Only consider under the guidance of a diabetologist.",
    "benefits.caution.ckd": "Chronic Kidney Disease (CKD)",
    "benefits.caution.ckd.desc": "The relationship between keto and kidney health is nuanced.",
    "benefits.caution.ckd.list1": "Concerns about long-term safety in advanced CKD",
    "benefits.caution.ckd.list2": "Must manage protein intake and electrolytes carefully",
    "benefits.caution.pregnancy": "Pregnancy & Breastfeeding",
    "benefits.caution.pregnancy.desc": "Insufficient safety data. Fetal development relies on a reliable supply of nutrients. The safest route is to avoid strict ketogenic diets.",
    "benefits.caution.ed": "History of Eating Disorders",
    "benefits.caution.ed.desc": "The rigid rules of keto can trigger disordered eating patterns. Ideally avoided unless approved by a mental health professional.",
    "benefits.caution.lipids": "Uncontrolled Dyslipidemia",
    "benefits.caution.lipids.desc": "Keto can cause a marked rise in LDL-cholesterol in some individuals.",
    "benefits.caution.lipids.note": "A cardiologist or lipid specialist should be involved.",
    "benefits.bottomline.title": "The Bottom Line",
    "benefits.bottomline.1": "It targets root causes like hyperinsulinaemia and visceral fat.",
    "benefits.bottomline.2": "It can deliver significant improvements in weight, blood sugar, and liver fat.",
    "benefits.bottomline.3": "It is not suitable, or only cautiously suitable, for certain medical conditions.",
    "benefits.bottomline.action": "Your next step shouldn't be starting keto tomorrow — it should be getting properly evaluated.",
    "benefits.bottomline.step1": "Talk to a healthcare professional.",
    "benefits.bottomline.step2": "Share your full medical history and lab results.",
    "benefits.bottomline.step3": "Discuss whether a ketogenic strategy fits your health profile.",
    "benefits.bottomline.final": "Keto is a powerful tool — highly effective in the right hands, but not automatically the right choice for everyone.",
    // Guide Page
    "guide.back": "Back to Home",
    "guide.badge": "Practical Application",
    "guide.title": "Getting Started with Keto: The First Two Weeks",
    "guide.subtitle": "A step-by-step guide to navigating the induction phase, managing side effects, and setting yourself up for long-term success.",
    "guide.intro": "The first two weeks of a ketogenic diet are where the biggest metabolic changes happen. Your body is moving from sugar-burning to fat- and ketone-burning, your hormones are adjusting, and your brain is learning to run on a new fuel. This guide walks you through:",
    "guide.intro.list1": "How to prepare medically and safely",
    "guide.intro.list2": "What to expect day by day in the induction phase",
    "guide.intro.list3": "How to manage the \"keto flu\" and other side effects",
    "guide.intro.list4": "The habits that make long-term success much more likely",
    "guide.step1.title": "1. Medical Preparation",
    "guide.step1.intro": "Before embarking on a ketogenic diet, it's best to treat it like any other serious therapeutic intervention, not just a casual \"diet.\"",
    "guide.step1.history": "Review Your Health History",
    "guide.step1.history.desc": "Sit down with your healthcare provider and review:",
    "guide.step1.history.list1": "History of kidney disease, liver disease, pancreatitis, gallstones",
    "guide.step1.history.list2": "Any diagnosis of diabetes (type 1 or type 2) or prediabetes",
    "guide.step1.history.list3": "Cardiovascular risk factors: prior heart attack, stroke, very high cholesterol",
    "guide.step1.history.list4": "History of eating disorders or significant weight cycling",
    "guide.step1.history.note": "This helps determine whether keto is appropriate for you, or whether a gentler low-carb or Mediterranean-style approach might be safer.",
    "guide.step1.meds": "Review Medications",
    "guide.step1.meds.desc": "A ketogenic diet can change how your body responds to several drugs, especially:",
    "guide.step1.meds.list1": "Diabetes medications (insulin, sulfonylureas, SGLT2 inhibitors)",
    "guide.step1.meds.list2": "Blood pressure medications (you may need lower doses as weight and BP improve)",
    "guide.step1.meds.list3": "Diuretics and certain psychiatric or neurological medications",
    "guide.step1.meds.action1": "Adjust insulin doses before or shortly after you start",
    "guide.step1.meds.action2": "Reduce or change blood pressure meds to avoid dizziness or fainting",
    "guide.step1.meds.action3": "Plan more frequent follow-ups early on (e.g., in the first month)",
    "guide.step1.meds.warning": "If you're on medication, do not start a strict ketogenic diet without telling your doctor. Rapid improvements are great – but only if your treatment plan keeps up.",
    "guide.step1.labs": "Baseline Lab Work",
    "guide.step1.labs.desc": "Ask your provider about getting baseline tests such as:",
    "guide.step1.labs.1": "Fasting glucose and HbA1c",
    "guide.step1.labs.2": "Lipid panel (total cholesterol, LDL, HDL, triglycerides)",
    "guide.step1.labs.3": "Liver enzymes (ALT, AST, GGT)",
    "guide.step1.labs.4": "Kidney function (creatinine, eGFR)",
    "guide.step1.labs.5": "Basic electrolytes (sodium, potassium, magnesium)",
    "guide.step1.labs.note": "These values give you: A safety check before you start, and a reference point so you can see exactly how keto is affecting your health over time.",
    "guide.step1.env": "Choose a Start Date and Environment",
    "guide.step1.env.desc": "Set yourself up for success:",
    "guide.step1.env.1": "Pick a start date that's relatively low-stress (not the week of a big work deadline or vacation)",
    "guide.step1.env.2": "Clear your kitchen of obvious high-carb foods (sugary snacks, bread, pasta, juice, sweetened drinks)",
    "guide.step1.env.3": "Make sure you have simple keto-friendly staples on hand (eggs, meat/fish, non-starchy veggies, healthy fats, nuts, seeds) so you're not scrambling for food during the adaptation period",

    "guide.step2.title": "2. The Induction Phase (Days 1–14)",
    "guide.step2.intro": "This is where your body transitions into ketosis – the process of switching from glucose dependence to fat and ketone metabolism.",
    "guide.step2.metabolic": "What to Expect – Metabolically",
    "guide.step2.metabolic.desc": "During the first 3–14 days: Your glycogen stores (stored carbohydrate in liver and muscles) are depleted. Each gram of glycogen is stored with water, so when you use it, you lose water, too. This can cause a rapid drop on the scale (often 1–3 kg in the first week), which is mostly water plus some glycogen, not pure fat – but it's still a sign the shift has begun. As insulin drops, your body ramps up fat breakdown and ketone production. Blood ketones slowly rise as you move into nutritional ketosis.",
    "guide.step2.timeline": "A rough timeline (this varies by person):",
    "guide.step2.phase1.title": "Days 1–3 – \"Where did the carbs go?\"",
    "guide.step2.phase1.s1": "Strong cravings for sugar or starch",
    "guide.step2.phase1.s2": "Noticeable water loss and more frequent urination",
    "guide.step2.phase1.s3": "Possible headache, irritability, or \"brain fog\" as your brain is still mostly used to glucose",
    "guide.step2.phase2.title": "Days 4–7 – Entering ketosis",
    "guide.step2.phase2.s1": "Hunger often starts to decrease",
    "guide.step2.phase2.s2": "Energy may feel low or \"up and down\" as your body is still learning to use fat and ketones efficiently",
    "guide.step2.phase2.s3": "Keto breath (a slightly fruity/acetone smell) may appear",
    "guide.step2.phase3.title": "Days 7–14 – Early fat adaptation",
    "guide.step2.phase3.s1": "Many people begin to feel more stable energy and fewer cravings",
    "guide.step2.phase3.s2": "Mental clarity may improve as the brain uses more ketones",
    "guide.step2.phase3.s3": "Exercise may still feel harder than usual, especially high-intensity work, but daily activities often feel smoother",
    "guide.step2.flu.title": "The \"Keto Flu\"",
    "guide.step2.flu.desc": "The \"keto flu\" is not a virus – it's a constellation of temporary symptoms that some people experience during the metabolic switch, especially in the first week:",
    "guide.step2.flu.s1": "Headache",
    "guide.step2.flu.s2": "Fatigue or heavy limbs",
    "guide.step2.flu.s3": "Brain fog, difficulty concentrating",
    "guide.step2.flu.s4": "Nausea, mild dizziness",
    "guide.step2.flu.s5": "Muscle cramps or heart palpitations",
    "guide.step2.flu.s6": "Irritability or trouble sleeping",
    "guide.step2.flu.cause": "These symptoms are usually linked to: Electrolyte losses (sodium, potassium, magnesium) as you shed water, a sudden drop in carb intake without enough planning, and temporary mismatch between your energy needs and your still-adapting fat/ketone engines.",
    "guide.step2.flu.note": "The good news: with proper hydration, electrolytes, and smart pacing, most symptoms are mild and resolve within several days.",

    "guide.step3.title": "3. Managing Side Effects",
    "guide.step3.intro": "You don't have to \"tough it out.\" Most early side effects are manageable if you prepare for them.",
    "guide.step3.hydrate": "Stay Hydrated",
    "guide.step3.hydrate.desc": "Aim for regular fluid intake throughout the day, not just big gulps all at once. Plain water is great, but you may also benefit from:",
    "guide.step3.hydration.1": "Water & Mineral water",
    "guide.step3.hydration.2": "Herbal teas",
    "guide.step3.hydration.3": "Broths (for salt)",
    "guide.step3.hydration.rule": "As a rule of thumb: if your urine is very dark or you feel light-headed when standing, you likely need more fluids and electrolytes (and possibly a medication check with your doctor).",
    "guide.step3.electrolytes": "Electrolytes: Sodium, Potassium, Magnesium",
    "guide.step3.electrolytes.desc": "When insulin drops, your kidneys excrete more sodium and water. To compensate:",
    "guide.step3.sodium": "Sodium",
    "guide.step3.sodium.desc": "Lightly salt your food. Consider drinking a cup of salted broth or adding a pinch of salt to water once or twice a day, especially in the first week (if your doctor hasn't restricted sodium for blood pressure/heart issues).",
    "guide.step3.potassium": "Potassium",
    "guide.step3.potassium.desc": "Focus on keto-friendly potassium sources like leafy greens, avocado, mushrooms, and some nuts/seeds. Avoid over-the-counter potassium supplements unless recommended by your doctor (they can interact with certain meds and heart conditions).",
    "guide.step3.magnesium": "Magnesium",
    "guide.step3.magnesium.desc": "Many people benefit from a gentle magnesium supplement in the evening to help with muscle cramps and sleep quality. Food sources include pumpkin seeds, almonds, leafy greens, and dark chocolate (sugar-free or very low sugar).",
    "guide.step3.ease": "Ease Into It",
    "guide.step3.ease.desc": "If your symptoms are intense, you don't have to go from \"full carb\" to \"near zero\" overnight. Options:",
    "guide.step3.ease.1": "Step down carbs over 1–2 weeks (e.g., from 200 g → 100 g → 50 g) while increasing healthy fats",
    "guide.step3.ease.2": "Avoid layering extreme calorie restriction, intense new workouts, and keto induction all at once. Start with the carb change; adjust calories and training later",
    "guide.step3.ease.3": "Keep your meals simple and repeatable during the first two weeks so you're not also stressed about complex recipes",
    "guide.step3.exercise": "Adjusting Exercise",
    "guide.step3.exercise.desc": "During the first week or two:",
    "guide.step3.exercise.1": "It's normal for high-intensity exercise (sprints, heavy lifting to failure) to feel harder",
    "guide.step3.exercise.2": "Light movement like walking, mobility work, and gentle cycling often actually helps clear brain fog and improves mood",
    "guide.step3.exercise.3": "After adaptation, many people regain or improve performance, especially in endurance-type activities",
    "guide.step3.exercise.4": "If you feel dizzy, extremely short of breath, or unwell during exercise, stop and reassess hydration, electrolytes, and food intake, and talk to your doctor if it persists",
    "guide.step3.doctor": "When to Call Your Doctor",
    "guide.step3.doctor.desc": "Seek medical advice promptly if you experience:",
    "guide.step3.doctor.1": "Persistent vomiting or severe nausea",
    "guide.step3.doctor.2": "Extreme weakness, chest pain, or shortness of breath",
    "guide.step3.doctor.3": "Very high blood glucose and/or very high ketones if you have diabetes",
    "guide.step3.doctor.4": "Confusion, severe abdominal pain, or any symptom that feels \"not normal\" for you",
    "guide.step3.doctor.note": "Keto should never feel like an emergency. If it does, stop the diet and get checked.",

    "guide.longterm.title": "Long-Term Success",
    "guide.longterm.p1": "The goal is a sustainable pattern that fits your life.",
    "guide.longterm.p2": "Keto isn't about perfection – it's about building a way of eating that works for your body and your life.",
    "guide.step4.title": "4. Long-Term Success & Pitfalls",
    "guide.step4.intro": "The first two weeks are only the beginning. The biggest challenge with keto is not getting into ketosis – it's staying in a sustainable pattern that fits your life.",
    "guide.step4.why": "Find Your \"Why\"",
    "guide.step4.why.desc": "Long-term change is much easier when you're clear on your deep reasons:",
    "guide.step4.why.1": "Reducing medication",
    "guide.step4.why.2": "Having the energy to play with your kids",
    "guide.step4.why.3": "Preventing diabetes or reversing fatty liver",
    "guide.step4.why.4": "Being more confident and comfortable in your body",
    "guide.step4.why.note": "Write your \"why\" somewhere you'll see it often – on your phone, fridge, or journal.",
    "guide.step4.plan": "Plan Ahead",
    "guide.step4.plan.1": "Plan your meals (at least roughly) for the week so you're not making big decisions while hungry",
    "guide.step4.plan.2": "Keep go-to emergency options on hand (boiled eggs, canned fish, nuts, frozen low-carb veggies, ready-to-use salad greens)",
    "guide.step4.plan.3": "Think about social situations: what will you order at restaurants, what can you bring to gatherings, how will you respond to pressure to \"just have cake\"?",
    "guide.step4.plan.note": "A bit of planning reduces stress and makes it less likely you'll abandon keto at the first obstacle.",
    "guide.step4.support": "Build a Support System",
    "guide.step4.support.desc": "You don't have to do this alone:",
    "guide.step4.support.1": "Involve a partner, friend, or family member if possible",
    "guide.step4.support.2": "Consider joining a supportive community (online group, local meet-up, or structured program) that focuses on evidence-based keto, not fad advice",
    "guide.step4.support.3": "Work with a dietitian or nutrition professional familiar with low-carb and ketogenic diets if you can",
    "guide.step4.support.note": "Accountability and community significantly increase the odds of sticking with your changes long enough to see real results.",
    "guide.step4.pitfalls.title": "Common Pitfalls to Watch Out For",
    "guide.step4.pitfalls.nutrients": "Nutrient Deficiencies",
    "guide.step4.pitfalls.nutrients.desc": "Keto is not supposed to be just meat, cheese, and oils. To protect your health:",
    "guide.step4.pitfalls.nutrients.1": "Eat plenty of non-starchy vegetables (leafy greens, broccoli, cauliflower, zucchini, peppers, cabbage, etc.)",
    "guide.step4.pitfalls.nutrients.2": "Include a variety of whole-food fats: olive oil, avocado, nuts, seeds, fatty fish",
    "guide.step4.pitfalls.nutrients.3": "Consider a basic multivitamin/mineral if your intake is limited or you're in a very low-calorie phase",
    "guide.step4.pitfalls.nutrients.note": "\"Eat your veggies\" matters even more on keto, because they're a major source of fiber, potassium, magnesium, and antioxidants.",
    "guide.step4.pitfalls.stones": "Kidney Stones",
    "guide.step4.pitfalls.stones.desc": "Keto can slightly increase the risk of kidney stones in some people, particularly if:",
    "guide.step4.pitfalls.stones.1": "They are chronically under-hydrated",
    "guide.step4.pitfalls.stones.2": "They consume excessive protein",
    "guide.step4.pitfalls.stones.3": "They're prone to stones already",
    "guide.step4.pitfalls.stones.prevention": "To reduce risk:",
    "guide.step4.pitfalls.stones.prevention.1": "Stay well-hydrated (especially if your urine is dark)",
    "guide.step4.pitfalls.stones.prevention.2": "Don't turn keto into an all-protein diet – keep protein moderate, fat as the main energy source",
    "guide.step4.pitfalls.stones.prevention.3": "Talk to your doctor if you have a history of stones; they may suggest strategies like adequate calcium intake and more citrate (e.g., lemon water)",
    "guide.step4.pitfalls.ldl": "Elevated LDL Cholesterol",
    "guide.step4.pitfalls.ldl.desc": "Many people see better triglycerides and HDL on keto, but a subset experience a significant rise in LDL.",
    "guide.step4.pitfalls.ldl.management": "To manage this:",
    "guide.step4.pitfalls.ldl.management.1": "Emphasize unsaturated fats (olive oil, avocado, nuts, seeds, fatty fish) over large amounts of butter, cream, and processed meats",
    "guide.step4.pitfalls.ldl.management.2": "Get lipid panels checked regularly, especially if you or your family have a history of heart disease",
    "guide.step4.pitfalls.ldl.management.3": "If LDL rises substantially, discuss with your doctor whether to: modify the type of fats you're eating, slightly increase carbs and transition to a more moderate low-carb approach, or consider other therapies, if appropriate",
    "guide.conclusion.title": "The Take-Home Message",
    "guide.conclusion.desc": "The first two weeks of keto are a metabolic reboot: Your body is learning to burn fat and ketones. Your hormones and electrolytes are rebalancing. You're building new habits (and probably breaking some old ones).",
    "guide.conclusion.success": "Go in prepared, supported, and informed, and those early days can set the stage for:",
    "guide.conclusion.success.1": "Better weight control",
    "guide.conclusion.success.2": "Improved metabolic health",
    "guide.conclusion.success.3": "More stable energy and appetite",
    "guide.conclusion.final": "Keto isn't about perfection – it's about building a way of eating that works for your body and your life.",
    "guide.recipes.title": "Keto Recipe Ideas",
    "guide.recipes.subtitle": "Simple, delicious recipes to get you started on your keto journey",
    "guide.recipes.breakfast.title": "Breakfast: Keto Scrambled Eggs with Avocado",
    "guide.recipes.breakfast.desc": "A protein-rich start to your day that keeps you satisfied until lunch.",
    "guide.recipes.breakfast.ingredients": "Ingredients:",
    "guide.recipes.breakfast.ingredients.list": "3 large eggs, 1 tbsp butter, 1/2 avocado, salt, pepper, fresh herbs (optional)",
    "guide.recipes.breakfast.instructions": "Instructions:",
    "guide.recipes.breakfast.instructions.list": "Scramble eggs in butter over medium heat. Serve with sliced avocado, season with salt and pepper. Garnish with fresh herbs if desired.",
    "guide.recipes.lunch.title": "Lunch: Grilled Chicken Salad",
    "guide.recipes.lunch.desc": "A refreshing, nutrient-dense meal perfect for midday energy.",
    "guide.recipes.lunch.ingredients": "Ingredients:",
    "guide.recipes.lunch.ingredients.list": "150g grilled chicken breast, mixed greens, cherry tomatoes, cucumber, olive oil, lemon juice, feta cheese (optional)",
    "guide.recipes.lunch.instructions": "Instructions:",
    "guide.recipes.lunch.instructions.list": "Grill chicken and slice. Toss greens with vegetables. Drizzle with olive oil and lemon juice. Top with chicken and feta cheese.",
    "guide.recipes.dinner.title": "Dinner: Salmon with Roasted Vegetables",
    "guide.recipes.dinner.desc": "A satisfying dinner rich in omega-3s and healthy fats.",
    "guide.recipes.dinner.ingredients": "Ingredients:",
    "guide.recipes.dinner.ingredients.list": "200g salmon fillet, broccoli, cauliflower, bell peppers, olive oil, garlic, herbs, lemon",
    "guide.recipes.dinner.instructions": "Instructions:",
    "guide.recipes.dinner.instructions.list": "Season salmon and roast at 200°C for 15-20 minutes. Toss vegetables in olive oil and roast alongside. Serve with lemon wedges.",
    "guide.recipes.dessert.title": "Dessert: Keto Chocolate Mousse",
    "guide.recipes.dessert.desc": "A rich, satisfying dessert without the sugar crash.",
    "guide.recipes.dessert.ingredients": "Ingredients:",
    "guide.recipes.dessert.ingredients.list": "200ml heavy cream, 2 tbsp unsweetened cocoa powder, 2-3 tbsp erythritol or stevia, vanilla extract",
    "guide.recipes.dessert.instructions": "Instructions:",
    "guide.recipes.dessert.instructions.list": "Whip cream until soft peaks form. Fold in cocoa powder, sweetener, and vanilla. Chill for at least 1 hour before serving.",
    "guide.recipes.snack.title": "Snack & Drink: Keto Smoothie",
    "guide.recipes.snack.desc": "A quick, energizing snack or meal replacement packed with healthy fats.",
    "guide.recipes.snack.ingredients": "Ingredients:",
    "guide.recipes.snack.ingredients.list": "1/2 avocado, 1 cup unsweetened almond milk, 1 tbsp almond butter, 1 scoop protein powder (optional), ice cubes",
    "guide.recipes.snack.instructions": "Instructions:",
    "guide.recipes.snack.instructions.list": "Blend all ingredients until smooth. Add ice for a colder drink. Enjoy as a snack or light meal.",

    // BMI Calculator
    "bmi.title": "BMI Calculator",
    "bmi.height": "Height",
    "bmi.weight": "Weight",
    "bmi.calculate": "Calculate BMI",
    "bmi.result": "Your BMI",
    "bmi.underweight": "Underweight",
    "bmi.normal": "Normal weight",
    "bmi.overweight": "Overweight",
    "bmi.obese": "Obese",
  },
  es: {
    // Navigation
    "nav.home": "Inicio",
    "nav.science": "La Ciencia",
    "nav.benefits": "Beneficios y Riesgos",
    "nav.guide": "Guía de Inicio",
    "nav.getStarted": "Empezar",
    
    // Home
    "home.badge": "Nutrición Respaldada por la Ciencia",
    "home.title": "Desbloquea tu Salud Metabólica: La Guía Definitiva Keto",
    "home.subtitle": "Una exploración científica de cómo la dieta cetogénica puede transformar su metabolismo, desde los mecanismos moleculares dentro de sus células hasta la aplicación en el mundo real para la pérdida de peso, la diabetes tipo 2, el hígado graso y el síndrome metabólico.",
    "home.subtitle2": "Aprenda a cambiar de forma segura de la dependencia del azúcar a la quema de grasa, mejorar la sensibilidad a la insulina y apoyar la salud a largo plazo con estrategias cetogénicas basadas en evidencia.",
    "home.cta.start": "Comienza tu Viaje",
    "home.cta.science": "Explora la Ciencia",
    "home.card.metabolic": "Cambio Metabólico",
    "home.card.metabolic.desc": "Cambia del metabolismo de glucosa al de grasa para energía sostenida.",
    "home.benefits.title": "Más Que Solo Pérdida de Peso",
    "home.benefits.subtitle": "La investigación moderna revela que las cetonas son poderosas moléculas de señalización que regulan procesos celulares críticos.",
    "home.card.cognitive": "Función Cognitiva",
    "home.card.neuroprotection": "Neuroprotección",
    "home.card.neuroprotection.desc": "Las cetonas proporcionan combustible estable para el cerebro, mejorando la eficiencia mitocondrial y reduciendo la neuroinflamación. La investigación sugiere beneficios potenciales para el rendimiento cognitivo.",
    "home.card.metabolic_health": "Salud Metabólica",
    "home.card.inflammation": "Control de Inflamación",
    "home.card.inflammation.desc": "La inflamación crónica impulsa la enfermedad metabólica. El BHB inhibe directamente el inflamasoma NLRP3, reduciendo las citoquinas inflamatorias y apoyando tejidos más saludables.",
    "home.card.cardio": "Cardiovascular",
    "home.card.weight": "Control de Peso",
    "home.card.weight.desc": "Keto reduce la insulina, desbloqueando las reservas de grasa y reduciendo las hormonas del hambre como la grelina. Este cambio metabólico apoya la pérdida de peso sostenible.",
    "home.how.title": "Cómo Funciona la Dieta Cetogénica",
    "home.how.desc": "En una dieta occidental estándar, la mayoría de las células funcionan principalmente con glucosa. La dieta cetogénica cambia fundamentalmente este paradigma metabólico. Al restringir la ingesta de carbohidratos y aumentar las grasas saludables, el cuerpo entra en un estado de cetosis.",
    "home.how.fuel": "Combustible Eficiente",
    "home.how.fuel.desc": "Las cetonas son solubles en agua y se transportan fácilmente al cerebro y los músculos, proporcionando una fuente de energía limpia.",
    "home.how.hormones": "Equilibrio Hormonal",
    "home.how.hormones.desc": "Los niveles más bajos de insulina desbloquean la grasa almacenada para obtener energía y mejoran la sensibilidad a la insulina con el tiempo.",
    "home.how.deepdive": "Lee la Inmersión Profunda Molecular",
    "home.cta.transform": "¿Listo para Transformar tu Salud?",
    "home.cta.transform.desc": "Obtén la guía completa para comenzar keto de manera segura, manejar los efectos secundarios y lograr el éxito a largo plazo.",
    "home.cta.check": "Verificar Indicaciones",

    // Footer
    "footer.desc": "Un recurso integral respaldado por la ciencia para comprender e implementar la dieta cetogénica de manera segura y efectiva.",
    "footer.content": "Contenido",
    "footer.legal": "Legal",
    "footer.privacy": "Política de Privacidad",
    "footer.terms": "Términos de Servicio",
    "footer.disclaimer": "Descargo Médico",
    "footer.language": "Idioma",
    "footer.rights": "KetoMindset. Todos los derechos reservados. La información es solo para fines educativos.",

    // Science Page
    "science.back": "Volver al Inicio",
    "science.badge": "Mecanismos Moleculares",
    "science.title": "Cómo Funciona la Dieta Cetogénica: Una Inmersión Profunda Molecular",
    "science.subtitle": "Entendiendo el cambio metabólico de glucosa a metabolismo de grasas y el poder de señalización de los cuerpos cetónicos.",
    "science.section1.title": "De Glucosa a Metabolismo de Grasas",
    "science.section1.p1": "En una dieta occidental típica, nuestras células funcionan principalmente con glucosa. Después de una comida rica en carbohidratos, la glucosa en sangre aumenta, lo que hace que el páncreas libere insulina. La insulina ayuda a las células a absorber glucosa y almacenar el exceso de energía como glucógeno y grasa, mientras suprime la descomposición de la grasa en el tejido adiposo.",
    "science.section1.p2": "La dieta cetogénica cambia fundamentalmente este paradigma. Al restringir la ingesta de carbohidratos a < 50 gramos por día (típicamente 5–10% de la energía total) y aumentar la ingesta de grasas a aproximadamente 70–80% de las calorías, reduce la insulina y obliga al cuerpo a buscar un combustible alternativo. Durante varios días, esto impulsa al hígado a la cetogénesis, produciendo cuerpos cetónicos e iniciando la cetosis nutricional.",
    "science.card.triggers": "Desencadenantes del Cambio Metabólico",
    "science.card.triggers.desc": "Una vez que se restringen los carbohidratos y cae la insulina, comienza una cascada de eventos metabólicos:",
    "science.card.insulin": "Insulina Baja",
    "science.card.insulin.desc1": "Los niveles de glucosa e insulina en sangre bajan significativamente.",
    "science.card.insulin.desc2": "La insulina baja elimina el \"freno\" en la descomposición de la grasa.",
    "science.card.insulin.desc3": "Las células se vuelven más sensibles a la insulina con el tiempo, mejorando la salud metabólica.",
    "science.card.fat": "Descomposición de Grasa (Lipólisis)",
    "science.card.fat.desc1": "En el tejido adiposo, se activa la lipasa sensible a hormonas (HSL).",
    "science.card.fat.desc2": "La HSL descompone los triglicéridos almacenados en ácidos grasos libres (FFA) y glicerol.",
    "science.card.fat.desc3": "Los FFA viajan a través del torrente sanguíneo al hígado y otros tejidos como una fuente importante de combustible.",
    "science.card.ketone": "Producción de Cetonas (Cetogénesis)",
    "science.card.ketone.desc1": "Dentro de las mitocondrias de las células hepáticas, los ácidos grasos libres sufren β-oxidación, generando acetil-CoA.",
    "science.card.ketone.desc2": "El exceso de acetil-CoA se dirige a la cetogénesis, produciendo cuerpos cetónicos: β-hidroxibutirato (BHB), Acetoacetato (AcAc) y Acetona.",
    "science.card.ketone.desc3": "Estas cetonas se liberan luego al torrente sanguíneo y se convierten en un combustible central para el cerebro, el corazón y los músculos.",
    "science.card.note": "La cetosis nutricional (BHB ~0.5–3.0 mmol/L) no es lo mismo que la cetoacidosis diabética. En la cetosis nutricional, el pH permanece normal, la insulina es baja pero presente, y el proceso está estrictamente regulado.",
    "science.section2.title": "Cetonas como Fuente de Combustible Superior",
    "science.section2.p1": "Los cuerpos cetónicos son solubles en agua, lo que significa que viajan fácilmente a través del torrente sanguíneo y a través de las membranas celulares. Las células en el músculo, el corazón y el cerebro expresan transportadores (MCT) que absorben rápidamente las cetonas. Dentro de la célula, las cetonas se convierten nuevamente en acetil-CoA y entran en el ciclo de Krebs (ciclo TCA) para producir ATP, la moneda de energía universal de la célula.",
    "science.section2.subtitle": "Combustible Cerebral Eficiente y Flexibilidad Metabólica",
    "science.section2.p2": "Una ventaja clave de la cetosis es que el cerebro puede obtener una parte significativa de su energía de las cetonas, reduciendo su dependencia de la glucosa. Esto:",
    "science.section2.list1": "Suaviza las fluctuaciones de azúcar en sangre",
    "science.section2.list2": "Puede reducir los \"bajones de energía\" asociados con la alimentación alta en carbohidratos",
    "science.section2.list3": "Ayuda a explicar por qué muchas personas en cetosis reportan un pensamiento más claro y un enfoque más estable",
    "science.section2.flexibility": "Esta capacidad de cambiar entre combustibles (glucosa cuando está disponible, cetonas cuando los carbohidratos son bajos) se llama flexibilidad metabólica, y es un sello distintivo de un metabolismo más saludable.",
    "science.transport.title": "Visualizando el Transporte de Cetonas",
    "science.transport.1": "Generado en el hígado a partir de ácidos grasos",
    "science.transport.2": "Liberado en el torrente sanguíneo",
    "science.transport.3": "Transportado rápidamente a través de portadores específicos a órganos hambrientos de energía",
    "science.transport.4": "Convertido en ATP dentro de las mitocondrias con una eficiencia impresionante",
    "science.transport.note": "A diferencia de los ácidos grasos de cadena larga, los cuerpos cetónicos no requieren un empaquetado complejo en lipoproteínas; se mueven libremente en la sangre, lo que los convierte en una fuente de energía rápida, limpia y accesible.",
    "science.infographic.title": "Por Qué Keto Funciona para la Pérdida de Peso (Especialmente en Obesidad)",
    "science.infographic.desc": "Esta infografía desglosa los mecanismos científicos por los cuales las dietas cetogénicas contribuyen a la pérdida de peso y mejoras metabólicas. Explica cuatro vías clave: supresión del apetito a través de la regulación de hormonas del hambre, mayor gasto energético, reducción de insulina y movilización de grasa, y la magnitud de los resultados de pérdida de peso. Basado en meta-análisis y ensayos controlados aleatorios (2024-2025), las dietas cetogénicas producen una pérdida de peso superior en la obesidad a través de múltiples mecanismos complementarios, con mejores resultados cuando se combinan con una ingesta adecuada de proteínas y entrenamiento de resistencia.",
    "science.section3.title": "Más Que Solo Combustible: Moléculas de Señalización",
    "science.section3.p1": "La investigación moderna muestra que las cetonas no son solo portadores de energía pasivos. Son moléculas de señalización bioactivas que influyen en la inflamación, la expresión génica, las defensas contra el estrés oxidativo y las vías metabólicas involucradas en el envejecimiento y las enfermedades crónicas.",
    "science.card.anti_inflammatory": "Efectos Antiinflamatorios",
    "science.card.anti_inflammatory.subtitle": "BHB y el inflamasoma NLRP3",
    "science.card.anti_inflammatory.desc1": "El inflamasoma NLRP3 es un complejo intracelular que amplifica la inflamación y está implicado en condiciones como la obesidad, la diabetes tipo 2 y las enfermedades cardiovasculares.",
    "science.card.anti_inflammatory.desc2": "BHB inhibe directamente la activación de NLRP3, reduciendo la producción de citocinas inflamatorias como IL-1β e IL-18.",
    "science.card.anti_inflammatory.desc3": "Esta amortiguación de la inflamación crónica de bajo grado puede apoyar vasos sanguíneos más saludables, tejidos metabólicos y potencialmente la función cerebral con el tiempo.",
    "science.card.anti_inflammatory.desc4": "En otras palabras, las cetonas no solo alimentan las células, sino que ayudan a calmar la señalización inflamatoria a nivel molecular.",
    "science.card.epigenetic": "Regulación Epigenética",
    "science.card.epigenetic.subtitle": "BHB como señal epigenética",
    "science.card.epigenetic.desc1": "BHB también actúa como:",
    "science.card.epigenetic.list1": "Un inhibidor de la histona desacetilasa (HDAC)",
    "science.card.epigenetic.list2": "Un donante para la β-hidroxibutirilación de histonas",
    "science.card.epigenetic.desc2": "Estos procesos modifican cuán apretadamente está empaquetado el ADN y cómo se expresan los genes. A través de estos mecanismos epigenéticos, BHB puede:",
    "science.card.epigenetic.list3": "Regular al alza los genes involucrados en la defensa antioxidante y la resistencia al estrés oxidativo",
    "science.card.epigenetic.list4": "Influir en los genes vinculados al metabolismo energético y la función mitocondrial",
    "science.card.epigenetic.list5": "Potencialmente apoyar la longevidad celular y la resiliencia en tejidos como el corazón y el cerebro",
    "science.card.epigenetic.desc3": "Es por eso que los estados cetogénicos se están explorando no solo para trastornos metabólicos, sino también por sus implicaciones protectoras en enfermedades cardiovasculares y neurodegenerativas.",
    "science.references": "Referencias Científicas",

    // Benefits Page
    "benefits.back": "Volver al Inicio",
    "benefits.badge": "Indicaciones y Contraindicaciones",
    "benefits.title": "¿Es Keto Adecuado para Ti?",
    "benefits.subtitle": "Una mirada equilibrada y basada en la ciencia sobre quién puede beneficiarse más de una dieta cetogénica, y quién debe evitarla o usarla solo bajo estricta supervisión médica.",
    "benefits.intro": "La dieta cetogénica no es una solución única para todos. Para algunas personas, especialmente aquellas con obesidad y resistencia a la insulina, puede ser una herramienta terapéutica poderosa. Para otros, puede ser ineficaz, difícil de mantener o incluso insegura.",
    "benefits.section1.title": "¿Quién Puede Beneficiarse?",
    "benefits.card.obesity": "Obesidad y Síndrome Metabólico",
    "benefits.card.obesity.desc": "Para personas con sobrepeso u obesidad, especialmente aquellas con síndrome metabólico, las dietas cetogénicas producen consistentemente una pérdida de peso clínicamente significativa, a menudo mayor que las dietas bajas en grasa estándar a corto y mediano plazo.",
    "benefits.card.obesity.improvements": "Las mejoras comunes incluyen:",
    "benefits.card.obesity.list1": "Menor circunferencia de cintura",
    "benefits.card.obesity.list2": "Triglicéridos más bajos",
    "benefits.card.obesity.list3": "Colesterol HDL ('bueno') más alto",
    "benefits.card.obesity.list4": "Reducciones modestas en la presión arterial",
    "benefits.card.diabetes": "Diabetes Tipo 2",
    "benefits.card.diabetes.desc": "Para las personas con diabetes tipo 2 (DT2), la restricción de carbohidratos va directamente a la raíz del problema: la regulación alterada de la glucosa y la insulina.",
    "benefits.card.diabetes.list1": "Reducir significativamente la HbA1c",
    "benefits.card.diabetes.list2": "Reducir la glucosa e insulina en ayunas",
    "benefits.card.diabetes.list3": "Mejorar la sensibilidad a la insulina",
    "benefits.card.diabetes.list4": "Permitir a muchos pacientes reducir o suspender medicamentos",
    "benefits.card.diabetes.warning": "La dieta keto autodirigida sin apoyo profesional es riesgosa para las personas que toman medicamentos para reducir la glucosa.",
    "benefits.card.nafld": "Hígado Graso (NAFLD / MASLD)",
    "benefits.card.nafld.desc": "La evidencia emergente sugiere que las dietas cetogénicas pueden reducir el contenido de grasa hepática, disminuir las enzimas hepáticas y mejorar los marcadores de riesgo metabólico general.",
    "benefits.card.nafld.list1": "Reducir el contenido de grasa hepática",
    "benefits.card.nafld.list2": "Disminuir las enzimas hepáticas (ALT, AST, GGT)",
    "benefits.card.nafld.list3": "Disminuir la lipogénesis de novo",
    "benefits.card.pcos": "SOP (PCOS)",
    "benefits.card.pcos.desc": "En mujeres con SOP y sobrepeso/obesidad, las dietas cetogénicas pueden promover la pérdida de peso, mejorar la resistencia a la insulina y reducir los niveles de andrógenos.",
    "benefits.card.pcos.list1": "Promover la pérdida de peso",
    "benefits.card.pcos.list2": "Mejorar la resistencia a la insulina",
    "benefits.card.pcos.list3": "Mejorar la regularidad menstrual",
    "benefits.section2.title": "Contraindicaciones Absolutas",
    "benefits.contra.warning": "NO comiences una dieta cetogénica sin orientación especializada si tienes alguno de los siguientes:",
    "benefits.contra.group1": "Trastornos Metabólicos",
    "benefits.contra.1": "Trastornos conocidos de oxidación de ácidos grasos (ej. deficiencia de CPT-II)",
    "benefits.contra.2": "Defectos en el metabolismo de cuerpos cetónicos",
    "benefits.contra.group2": "Insuficiencia de Órganos",
    "benefits.contra.3": "Pancreatitis aguda o crónica severa",
    "benefits.contra.4": "Porfiria o insuficiencia hepática severa",
    "benefits.contra.note": "Estas condiciones son raras pero pueden convertir una dieta cetogénica en una emergencia médica.",
    "benefits.section3.title": "Contraindicaciones Relativas",
    "benefits.caution": "Estas situaciones no descartan automáticamente la dieta keto, pero exigen supervisión médica experimentada:",
    "benefits.caution.1": "Diabetes Tipo 1",
    "benefits.caution.1.desc": "La restricción agresiva de carbohidratos combinada con insulina insuficiente puede desencadenar cetoacidosis diabética (CAD).",
    "benefits.caution.1.note": "Considerar solo bajo la guía de un diabetólogo.",
    "benefits.caution.ckd": "Enfermedad Renal Crónica (ERC)",
    "benefits.caution.ckd.desc": "La relación entre keto y la salud renal es matizada.",
    "benefits.caution.ckd.list1": "Preocupaciones sobre la seguridad a largo plazo en ERC avanzada",
    "benefits.caution.ckd.list2": "Debe manejarse cuidadosamente la ingesta de proteínas y electrolitos",
    "benefits.caution.pregnancy": "Embarazo y Lactancia",
    "benefits.caution.pregnancy.desc": "Datos de seguridad insuficientes. El desarrollo fetal depende de un suministro confiable de nutrientes. La ruta más segura es evitar dietas cetogénicas estrictas.",
    "benefits.caution.ed": "Historial de Trastornos Alimenticios",
    "benefits.caution.ed.desc": "Las reglas rígidas de keto pueden desencadenar patrones de alimentación desordenada. Idealmente evitar a menos que sea aprobado por un profesional de salud mental.",
    "benefits.caution.lipids": "Dislipidemia No Controlada",
    "benefits.caution.lipids.desc": "Keto puede causar un aumento marcado en el colesterol LDL en algunos individuos.",
    "benefits.caution.lipids.note": "Debe participar un cardiólogo o especialista en lípidos.",
    "benefits.bottomline.title": "La Conclusión",
    "benefits.bottomline.1": "Apunta a causas fundamentales como la hiperinsulinemia y la grasa visceral.",
    "benefits.bottomline.2": "Puede ofrecer mejoras significativas en peso, azúcar en sangre y grasa hepática.",
    "benefits.bottomline.3": "No es adecuada, o solo con precaución, para ciertas condiciones médicas.",
    "benefits.bottomline.action": "Tu próximo paso no debería ser comenzar keto mañana, sino ser evaluado adecuadamente.",
    "benefits.bottomline.step1": "Habla con un profesional de la salud.",
    "benefits.bottomline.step2": "Comparte tu historial médico completo y resultados de laboratorio.",
    "benefits.bottomline.step3": "Discute si una estrategia cetogénica se ajusta a tu perfil de salud.",
    "benefits.bottomline.final": "Keto es una herramienta poderosa, altamente efectiva en las manos adecuadas, pero no automáticamente la elección correcta para todos.",

    // Guide Page
    "guide.back": "Volver al Inicio",
    "guide.badge": "Aplicación Práctica",
    "guide.title": "Comenzando con Keto: Las Primeras Dos Semanas",
    "guide.subtitle": "Una guía paso a paso para navegar la fase de inducción, manejar efectos secundarios y prepararte para el éxito.",
    "guide.step1.title": "Preparación Médica",
    "guide.step1.history": "Revisa tu Historial Médico",
    "guide.step1.history.desc": "Siéntate con tu proveedor de salud y revisa:",
    "guide.step1.history.list1": "Historial de enfermedad renal/hepática, pancreatitis, cálculos biliares",
    "guide.step1.history.list2": "Diabetes (tipo 1 o 2) o prediabetes",
    "guide.step1.history.list3": "Factores de riesgo cardiovascular (ataque cardíaco, accidente cerebrovascular)",
    "guide.step1.history.list4": "Historial de trastornos alimentarios",
    "guide.step1.meds": "Revisar Medicamentos",
    "guide.step1.meds.desc": "Keto puede cambiar cómo responde tu cuerpo a los medicamentos (insulina, presión arterial, diuréticos).",
    "guide.step1.meds.warning": "Si tomas medicamentos, no comiences una dieta cetogénica estricta sin informar a tu médico.",
    "guide.step1.meds.list1": "Medicamentos para la diabetes (insulina, sulfonilureas)",
    "guide.step1.meds.list2": "Medicamentos para la presión arterial",
    "guide.step1.meds.list3": "Diuréticos o medicamentos psiquiátricos",
    "guide.step1.meds.action": "Las mejoras rápidas pueden requerir ajustes de dosis para evitar hipoglucemia o hipotensión.",
    "guide.step1.labs": "Análisis de Laboratorio Base",
    "guide.step1.labs.desc": "Pide a tu proveedor pruebas de base:",
    "guide.step1.labs.1": "Glucosa en ayunas y HbA1c",
    "guide.step1.labs.2": "Panel de lípidos (colesterol total, LDL, HDL, triglicéridos)",
    "guide.step1.labs.3": "Enzimas hepáticas (ALT, AST, GGT)",
    "guide.step1.labs.4": "Función renal (creatinina, eGFR)",
    "guide.step1.labs.5": "Electrolitos básicos",
    "guide.step1.env": "Configuración del Entorno",
    "guide.step1.env.1": "Elige una fecha de inicio con poco estrés",
    "guide.step1.env.2": "Limpia la cocina de alimentos altos en carbohidratos",
    "guide.step1.env.3": "Abastécete de alimentos básicos keto (huevos, carne, verduras)",
    "guide.step2.title": "La Fase de Inducción (Días 1-14)",
    "guide.step2.intro": "Aquí es donde tu cuerpo hace la transición a la cetosis: cambiando de la dependencia de la glucosa al metabolismo de grasas y cetonas.",
    "guide.step2.phase1.title": "Días 1–3: Agotamiento",
    "guide.step2.phase1.desc": "Las reservas de glucógeno se vacían, causando una rápida pérdida de peso de agua.",
    "guide.step2.phase1.s1": "Fuertes antojos de azúcar o almidón",
    "guide.step2.phase1.s2": "Rápida caída en la báscula (principalmente agua)",
    "guide.step2.phase1.s3": "Posible dolor de cabeza o irritabilidad",
    "guide.step2.phase2.title": "Días 4–7: Transición",
    "guide.step2.phase2.desc": "La insulina baja, la producción de cetonas aumenta.",
    "guide.step2.phase2.s1": "El hambre comienza a disminuir",
    "guide.step2.phase2.s2": "La energía puede fluctuar",
    "guide.step2.phase2.s3": "Puede aparecer aliento ceto (olor afrutado)",
    "guide.step2.phase3.title": "Días 7–14: Adaptación",
    "guide.step2.phase3.desc": "Comienza la adaptación temprana a la grasa.",
    "guide.step2.phase3.s1": "Energía más estable",
    "guide.step2.phase3.s2": "Claridad mental mejorada",
    "guide.step2.phase3.s3": "Las actividades diarias se sienten más fluidas",
    "guide.step2.flu.title": "La 'Gripe Keto'",
    "guide.step2.flu.desc": "Síntomas temporales debido a la pérdida de electrolitos y el cambio metabólico:",
    "guide.step2.flu.s1": "Dolor de cabeza y fatiga",
    "guide.step2.flu.s2": "Niebla mental",
    "guide.step2.flu.s3": "Náuseas",
    "guide.step2.flu.s4": "Mareos",
    "guide.step2.flu.s5": "Calambres musculares",
    "guide.step2.flu.s6": "Irritabilidad",
    "guide.step2.flu.note": "Con hidratación y electrolitos, la mayoría de los síntomas se resuelven rápidamente.",
    "guide.step3.title": "3. Manejo de Efectos Secundarios",
    "guide.step3.intro": "La mayoría de los efectos secundarios son manejables con preparación.",
    "guide.step3.hydrate": "Mantente Hidratado",
    "guide.step3.hydrate.desc": "Bebe agua, agua mineral, tés de hierbas y caldo de huesos.",
    "guide.step3.hydration.1": "Agua y agua mineral",
    "guide.step3.hydration.2": "Tés de hierbas",
    "guide.step3.hydration.3": "Caldos (para sal)",
    "guide.step3.hydration.rule": "Regla general: Si la orina es oscura o te sientes mareado, bebe más.",
    "guide.step3.electrolytes": "Electrolitos",
    "guide.step3.electrolytes.desc": "Reponer sodio, potasio y magnesio.",
    "guide.step3.sodium": "Sodio",
    "guide.step3.sodium.desc": "Sala tu comida. Bebe caldo salado si es necesario (a menos que esté restringido).",
    "guide.step3.potassium": "Potasio",
    "guide.step3.potassium.desc": "Come aguacate, verduras de hoja verde, champiñones. Evita suplementos a menos que se prescriban.",
    "guide.step3.magnesium": "Magnesio",
    "guide.step3.magnesium.desc": "Considera un suplemento suave por la noche. Come semillas de calabaza, almendras, chocolate negro.",
    "guide.step3.ease": "Tómatelo con Calma",
    "guide.step3.ease.desc": "No te apresures si los síntomas son intensos.",
    "guide.step3.ease.1": "Reduce los carbohidratos gradualmente",
    "guide.step3.ease.2": "No combines con entrenamientos nuevos intensos",
    "guide.step3.ease.3": "Mantén las comidas simples",
    "guide.step3.exercise": "Ajustando el Ejercicio",
    "guide.step3.exercise.1": "La alta intensidad puede sentirse más difícil inicialmente",
    "guide.step3.exercise.2": "El movimiento ligero ayuda a despejar la niebla mental",
    "guide.step3.exercise.3": "El rendimiento a menudo regresa después de la adaptación",
    "guide.step3.exercise.4": "Detente si te sientes mareado o mal",
    "guide.step3.doctor": "Cuándo Llamar a tu Médico",
    "guide.step3.doctor.1": "Vómitos/náuseas persistentes",
    "guide.step3.doctor.2": "Debilidad extrema/dolor en el pecho",
    "guide.step3.doctor.3": "Glucosa/cetonas muy altas",
    "guide.step3.doctor.4": "Dolor abdominal severo",
    "guide.step3.doctor.note": "Keto nunca debería sentirse como una emergencia.",
    "guide.longterm.title": "Éxito a Largo Plazo",
    "guide.longterm.p1": "El objetivo es un patrón sostenible que se adapte a tu vida.",
    "guide.longterm.p2": "Keto no se trata de perfección, se trata de construir una forma de comer que funcione para tu cuerpo y tu vida.",
    "guide.step4.title": "4. Éxito a Largo Plazo y Trampas",
    "guide.step4.intro": "La consistencia vence a la perfección.",
    "guide.step4.why": "Encuentra tu 'Por Qué'",
    "guide.step4.why.desc": "El cambio a largo plazo es más fácil cuando tienes claras tus razones profundas.",
    "guide.step4.why.1": "Reducir medicación / Revertir hígado graso",
    "guide.step4.why.2": "Energía para jugar con los niños",
    "guide.step4.why.3": "Claridad mental para el trabajo",
    "guide.step4.why.4": "La cetosis es una herramienta, no una religión. Si un día te sales, simplemente vuelve a empezar en la siguiente comida.",
    "guide.step4.pitfalls.title": "Errores Comunes",
    "guide.step4.pitfalls.1": "Comer en exceso nueces/queso (altos en calorías)",
    "guide.step4.pitfalls.2": "Productos 'Keto' procesados (a menudo detienen el progreso)",
    "guide.step4.pitfalls.3": "Ignorar las verduras (necesitas fibra/micronutrientes)",
    "guide.step4.pitfalls.4": "Obsesionarse con la báscula (usa medidas de cintura o ajuste de ropa)",
    "guide.conclusion.title": "Tu Viaje Comienza Ahora",
    "guide.conclusion.desc": "Keto no es solo una dieta; es una herramienta metabólica para recuperar tu salud. Comienza simple, mantente constante y escucha a tu cuerpo.",
    "guide.conclusion.final": "¡Tienes esto!",

    // BMI Calculator
    "bmi.title": "Calculadora de IMC",
    "bmi.height": "Altura",
    "bmi.weight": "Peso",
    "bmi.calculate": "Calcular IMC",
    "bmi.result": "Tu IMC",
    "bmi.underweight": "Bajo peso",
    "bmi.normal": "Peso normal",
    "bmi.overweight": "Sobrepeso",
    "bmi.obese": "Obesidad",
  },
  sk: {
    // Navigation
    "nav.home": "Domov",
    "nav.science": "Veda",
    "nav.benefits": "Výhody a riziká",
    "nav.guide": "Príručka",
    "nav.getStarted": "Začať",
    
    // Home
    "home.badge": "Vedecky podložená výživa",
    "home.title": "Odomknite svoje metabolické zdravie: Definitívna Keto príručka",
    "home.subtitle": "Vedecky podložený prieskum toho, ako ketogénna diéta môže transformovať váš metabolizmus – od molekulárnych mechanizmov vo vašich bunkách až po reálne využitie pri chudnutí, cukrovke 2. typu, stukovatení pečene a metabolickom syndróme.",
    "home.subtitle2": "Naučte sa, ako bezpečne prejsť zo závislosti na cukre na spaľovanie tukov, zlepšiť citlivosť na inzulín a podporiť dlhodobé zdravie pomocou ketogénnych stratégií založených na dôkazoch.",
    "home.cta.start": "Začnite svoju cestu",
    "home.cta.science": "Preskúmajte vedu",
    "home.card.metabolic": "Metabolický prepínač",
    "home.card.metabolic.desc": "Prechod z metabolizmu glukózy na metabolizmus tukov pre udržateľnú energiu.",
    "home.benefits.title": "Viac než len chudnutie",
    "home.benefits.subtitle": "Moderný výskum odhaľuje, že ketóny sú silné signálne molekuly, ktoré regulujú kritické bunkové procesy.",
    "home.card.cognitive": "Kognitívne funkcie",
    "home.card.neuroprotection": "Neuroprotekcia",
    "home.card.neuroprotection.desc": "Ketóny poskytujú stabilné palivo pre mozog, zvyšujú mitochondriálnu účinnosť a znižujú neurozápal. Výskum naznačuje potenciálne prínosy pre kognitívny výkon.",
    "home.card.metabolic_health": "Metabolické zdravie",
    "home.card.inflammation": "Kontrola zápalu",
    "home.card.inflammation.desc": "Chronický zápal poháňa metabolické ochorenia. BHB priamo inhibuje inflamazóm NLRP3, znižuje zápalové cytokíny a podporuje zdravšie tkanivá.",
    "home.card.cardio": "Kardiovaskulárne zdravie",
    "home.card.weight": "Riadenie hmotnosti",
    "home.card.weight.desc": "Keto znižuje inzulín, odomyká tukové zásoby a znižuje hormóny hladu, ako je ghrelín. Tento metabolický posun podporuje udržateľné chudnutie.",
    "home.how.title": "Ako funguje ketogénna diéta",
    "home.how.desc": "Pri štandardnej západnej strave funguje väčšina buniek primárne na glukózu. Ketogénna diéta zásadne mení túto metabolickú paradigmu. Obmedzením príjmu sacharidov a zvýšením zdravých tukov sa telo dostáva do stavu ketózy.",
    "home.how.fuel": "Efektívne palivo",
    "home.how.fuel.desc": "Ketóny sú rozpustné vo vode a ľahko sa transportujú do mozgu a svalov, čím poskytujú čistý zdroj energie.",
    "home.how.hormones": "Hormonálna rovnováha",
    "home.how.hormones.desc": "Nižšie hladiny inzulínu odomykajú uložený tuk pre energiu a časom zlepšujú citlivosť na inzulín.",
    "home.how.deepdive": "Prečítajte si molekulárnu hĺbkovú analýzu",
    "home.cta.transform": "Ste pripravení transformovať svoje zdravie?",
    "home.cta.transform.desc": "Získajte kompletnú príručku, ako bezpečne začať s keto, zvládať vedľajšie účinky a dosiahnuť dlhodobý úspech.",
    "home.cta.check": "Skontrolovať indikácie",

    // Footer
    "footer.desc": "Komplexný, vedecky podložený zdroj na pochopenie a implementáciu ketogénnej diéty bezpečným a efektívnym spôsobom.",
    "footer.content": "Obsah",
    "footer.legal": "Právne informácie",
    "footer.privacy": "Zásady ochrany osobných údajov",
    "footer.terms": "Podmienky služby",
    "footer.disclaimer": "Lekárske vyhlásenie",
    "footer.language": "Jazyk",
    "footer.rights": "KetoMindset. Všetky práva vyhradené. Informácie slúžia len na vzdelávacie účely.",
    
    // Science Page (Placeholders to prevent errors if visited)
    "science.back": "Späť na domov",
    "science.badge": "Molekulárne mechanizmy",
    "science.title": "Ako funguje ketogénna diéta: Molekulárna hĺbková analýza",
    "science.subtitle": "Pochopenie metabolického posunu z glukózy na metabolizmus tukov a signalizačnej sily ketónových telies.",
    "science.infographic.title": "Prečo Keto Funguje na Chudnutie (Obzvlášť pri Obezite)",
    "science.infographic.desc": "Táto infografika rozkladá vedecké mechanizmy, ktorými ketogénne diéty prispievajú k chudnutiu a metabolickým zlepšeniam. Vysvetľuje štyri kľúčové cesty: potlačenie chuti do jedla prostredníctvom regulácie hormónov hladu, zvýšený energetický výdaj, zníženie inzulínu a mobilizácia tukov, a rozsah výsledkov chudnutia. Na základe meta-analýz a randomizovaných kontrolovaných štúdií (2024-2025) produkujú ketogénne diéty nadradené chudnutie pri obezite prostredníctvom viacerých komplementárnych mechanizmov, s najlepšími výsledkami pri kombinácii s adekvátnym príjmom bielkovín a silovým tréningom.",
    "science.card.insulin": "Nízky inzulín",
    "science.card.fat": "Spaľovanie tukov",
    "science.card.ketone": "Produkcia ketónov",

    // Benefits Page (Placeholders)
    "benefits.title": "Je Keto pre vás to pravé?",
    "benefits.subtitle": "Vyvážený, vedecky podložený pohľad na to, kto môže z ketogénnej diéty profitovať najviac.",

    // Guide Page (Placeholders)
    "guide.title": "Začíname s Keto: Prvé dva týždne",
    "guide.subtitle": "Sprievodca krok za krokom na zvládnutie indukčnej fázy.",

    // BMI Calculator
    "bmi.title": "BMI Kalkulačka",
    "bmi.height": "Výška",
    "bmi.weight": "Hmotnosť",
    "bmi.calculate": "Vypočítať BMI",
    "bmi.result": "Vaše BMI",
    "bmi.underweight": "Podváha",
    "bmi.normal": "Normálna hmotnosť",
    "bmi.overweight": "Nadváha",
    "bmi.obese": "Obezita",
  },
  cn: {
    // Navigation
    "nav.home": "首页",
    "nav.science": "科学原理",
    "nav.benefits": "益处与风险",
    "nav.guide": "入门指南",
    "nav.getStarted": "立即开始",
    
    // Home
    "home.badge": "科学循证营养",
    "home.title": "解锁代谢健康：生酮饮食终极指南",
    "home.subtitle": "科学探索生酮饮食如何改变您的新陈代谢——从细胞内的分子机制到减肥、2型糖尿病、脂肪肝和代谢综合征的实际应用。",
    "home.subtitle2": "了解如何安全地从依赖糖分转变为燃烧脂肪，提高胰岛素敏感性，并通过基于证据的生酮策略支持长期健康。",
    "home.cta.start": "开启您的旅程",
    "home.cta.science": "探索科学原理",
    "home.card.metabolic": "代谢转换",
    "home.card.metabolic.desc": "从葡萄糖代谢转向脂肪代谢，获得持久能量。",
    "home.benefits.title": "不仅仅是减肥",
    "home.benefits.subtitle": "现代研究表明，酮体不仅是燃料，更是调节关键细胞过程的强大信号分子。",
    "home.card.cognitive": "认知功能",
    "home.card.neuroprotection": "神经保护",
    "home.card.neuroprotection.desc": "酮体为大脑提供稳定的燃料，提高线粒体效率并减少神经炎症。研究表明对认知表现和神经退行性疾病有潜在益处。",
    "home.card.metabolic_health": "代谢健康",
    "home.card.inflammation": "炎症控制",
    "home.card.inflammation.desc": "慢性炎症驱动代谢疾病。BHB直接抑制NLRP3炎症小体，减少炎症细胞因子并支持更健康的组织。",
    "home.card.cardio": "心血管健康",
    "home.card.weight": "体重管理",
    "home.card.weight.desc": "生酮降低胰岛素，解锁脂肪储存并减少饥饿激素（如生长素释放肽）。这种代谢转变支持可持续的减肥并改善心脏代谢风险标志物。",
    "home.how.title": "生酮饮食如何运作",
    "home.how.desc": "在标准西方饮食中，大多数细胞主要依靠葡萄糖运行。生酮饮食从根本上改变了这种代谢范式。通过限制碳水化合物摄入并增加健康脂肪，身体进入酮症状态。",
    "home.how.fuel": "高效燃料",
    "home.how.fuel.desc": "酮体是水溶性的，易于输送到大脑和肌肉，提供清洁燃烧的能源。",
    "home.how.hormones": "荷尔蒙平衡",
    "home.how.hormones.desc": "较低的胰岛素水平释放储存的脂肪用于能量，并随着时间的推移改善胰岛素敏感性。",
    "home.how.deepdive": "阅读分子深度解析",
    "home.cta.transform": "准备好改变您的健康了吗？",
    "home.cta.transform.desc": "获取安全开始生酮、管理副作用和实现长期成功的完整指南。",
    "home.cta.check": "查看适应症",

    // Footer
    "footer.desc": "一个全面、科学支持的资源，用于安全有效地理解和实施生酮饮食。",
    "footer.content": "内容",
    "footer.legal": "法律",
    "footer.privacy": "隐私政策",
    "footer.terms": "服务条款",
    "footer.disclaimer": "医疗免责声明",
    "footer.language": "语言",
    "footer.rights": "KetoMindset. 版权所有. 信息仅供教育目的。",

    // Science Page
    "science.back": "返回首页",
    "science.badge": "分子机制",
    "science.title": "生酮饮食如何运作：分子深度解析",
    "science.subtitle": "了解从葡萄糖到脂肪代谢的代谢转变以及酮体的信号传递能力。",
    "science.section1.title": "从葡萄糖到脂肪代谢",
    "science.section1.p1": "在典型的西方饮食中，我们的细胞主要依靠葡萄糖运行。进食富含碳水化合物的一餐后，血糖升高，促使胰腺释放胰岛素。胰岛素帮助细胞吸收葡萄糖并将其作为糖原和脂肪储存多余能量，同时抑制脂肪组织中的脂肪分解。",
    "science.section1.p2": "生酮饮食从根本上改变了这种范式。通过将碳水化合物摄入量限制在每天 < 50 克（通常占总能量的 5–10%）并将脂肪摄入量增加到约 70–80%，您可以降低胰岛素并迫使身体寻找替代燃料。几天后，这会驱动肝脏进行生酮作用，产生酮体并启动营养性酮症。",
    "science.card.triggers": "代谢转变触发因素",
    "science.card.triggers.desc": "一旦限制碳水化合物且胰岛素下降，一系列代谢事件就开始了：",
    "science.card.insulin": "低胰岛素",
    "science.card.insulin.desc1": "血糖和胰岛素水平显著下降。",
    "science.card.insulin.desc2": "低胰岛素消除了脂肪分解的“刹车”。",
    "science.card.insulin.desc3": "细胞随着时间的推移对胰岛素变得更加敏感，从而改善代谢健康。",
    "science.card.fat": "脂肪分解（脂解）",
    "science.card.fat.desc1": "在脂肪组织中，激素敏感性脂肪酶 (HSL) 被激活。",
    "science.card.fat.desc2": "HSL 将储存的甘油三酯分解为游离脂肪酸 (FFA) 和甘油。",
    "science.card.fat.desc3": "FFA 通过血液输送到肝脏和其他组织，作为主要的燃料来源。",
    "science.card.ketone": "酮体产生（生酮作用）",
    "science.card.ketone.desc1": "在肝细胞的线粒体内，游离脂肪酸进行 β-氧化，生成乙酰辅酶 A。",
    "science.card.ketone.desc2": "过量的乙酰辅酶 A 进入生酮作用，产生酮体：β-羟基丁酸 (BHB)、乙酰乙酸 (AcAc) 和丙酮。",
    "science.card.ketone.desc3": "这些酮体随后被释放到血液中，成为大脑、心脏和肌肉的核心燃料。",
    "science.card.note": "营养性酮症 (BHB ~0.5–3.0 mmol/L) 与糖尿病酮症酸中毒不同。在营养性酮症中，pH 值保持正常，胰岛素水平低但存在，并且该过程受到严格调节。",
    "science.section2.title": "酮体作为优质燃料来源",
    "science.section2.p1": "酮体是水溶性的，这意味着它们很容易通过血液输送并穿过细胞膜。肌肉、心脏和大脑中的细胞表达转运蛋白 (MCT)，可以快速摄取酮体。在细胞内，酮体被转化回乙酰辅酶 A 并进入克雷布斯循环 (TCA 循环) 以产生 ATP——细胞的通用能量货币。",
    "science.section2.subtitle": "高效的大脑燃料与代谢灵活性",
    "science.section2.p2": "酮症的一个关键优势是，大脑可以从酮体中获得很大一部分能量，减少对葡萄糖的依赖。这：",
    "science.section2.list1": "平滑血糖波动",
    "science.section2.list2": "可以减少与高碳水化合物饮食相关的“能量崩溃”",
    "science.section2.list3": "有助于解释为什么许多处于酮症状态的人报告思维更清晰、注意力更稳定",
    "science.section2.flexibility": "这种在燃料之间切换的能力——有葡萄糖时用葡萄糖，碳水化合物低时用酮体——被称为代谢灵活性，这是更健康代谢的标志。",
    "science.transport.title": "可视化酮体运输",
    "science.transport.1": "在肝脏中由脂肪酸生成",
    "science.transport.2": "释放到血液中",
    "science.transport.3": "通过特定载体快速输送到能量饥渴的器官",
    "science.transport.4": "在线粒体内以惊人的效率转化为 ATP",
    "science.transport.note": "与长链脂肪酸不同，酮体不需要在脂蛋白中进行复杂的包装；它们在血液中自由移动，使其成为一种快速、清洁且易于获取的能量来源。",
    "science.infographic.title": "为什么生酮饮食对减肥有效（特别是肥胖症）",
    "science.infographic.desc": "这张信息图分解了生酮饮食如何促进减肥和代谢改善的科学机制。它解释了四个关键途径：通过饥饿激素调节抑制食欲、增加能量消耗、降低胰岛素和脂肪动员，以及减肥结果的幅度。基于荟萃分析和随机对照试验（2024-2025），生酮饮食通过多种互补机制在肥胖症中产生更优的减肥效果，当与充足的蛋白质摄入和阻力训练结合时效果最佳。",
    "science.section3.title": "不仅仅是燃料：信号分子",
    "science.section3.p1": "现代研究表明，酮体不仅仅是被动的能量载体。它们是具有生物活性的信号分子，影响炎症、基因表达、氧化应激防御以及涉及衰老和慢性疾病的代谢途径。",
    "science.card.anti_inflammatory": "抗炎作用",
    "science.card.anti_inflammatory.subtitle": "BHB 与 NLRP3 炎症小体",
    "science.card.anti_inflammatory.desc1": "NLRP3 炎症小体是一种细胞内复合物，会放大炎症，并与肥胖、2 型糖尿病和心血管疾病等疾病有关。",
    "science.card.anti_inflammatory.desc2": "BHB 直接抑制 NLRP3 激活，减少炎症细胞因子如 IL-1β 和 IL-18 的产生。",
    "science.card.anti_inflammatory.desc3": "这种对慢性低度炎症的抑制可以支持更健康的血管、代谢组织，并随着时间的推移可能支持大脑功能。",
    "science.card.anti_inflammatory.desc4": "换句话说，酮体不仅仅为细胞提供燃料——它们有助于在分子水平上平息炎症信号。",
    "science.card.epigenetic": "表观遗传调节",
    "science.card.epigenetic.subtitle": "BHB 作为表观遗传信号",
    "science.card.epigenetic.desc1": "BHB 还充当：",
    "science.card.epigenetic.list1": "组蛋白去乙酰化酶 (HDAC) 抑制剂",
    "science.card.epigenetic.list2": "组蛋白 β-羟基丁酰化的供体",
    "science.card.epigenetic.desc2": "这些过程改变了 DNA 包装的紧密程度以及基因的表达方式。通过这些表观遗传机制，BHB 可以：",
    "science.card.epigenetic.list3": "上调涉及抗氧化防御和氧化应激抵抗的基因",
    "science.card.epigenetic.list4": "影响与能量代谢和线粒体功能相关的基因",
    "science.card.epigenetic.list5": "可能支持心脏和大脑等组织的细胞寿命和恢复力",
    "science.card.epigenetic.desc3": "这就是为什么生酮状态不仅被探索用于代谢紊乱，还被探索用于其在心血管和神经退行性疾病中的保护意义。",
    "science.references": "科学参考文献",

    // Benefits Page
    "benefits.back": "返回首页",
    "benefits.badge": "适应症与禁忌症",
    "benefits.title": "生酮适合您吗？",
    "benefits.subtitle": "平衡、科学地看待谁可以从生酮饮食中获益最多——以及谁应该避免或仅在密切医疗监督下使用。",
    "benefits.intro": "生酮饮食不是万能的解决方案。对于某些人，特别是肥胖和胰岛素抵抗者，它可以是一个强大的治疗工具。对于其他人，它可能无效、难以维持，甚至不安全。",
    "benefits.section1.title": "谁可以受益？",
    "benefits.card.obesity": "肥胖与代谢综合征",
    "benefits.card.obesity.desc": "对于超重或肥胖的个体，特别是患有代谢综合征的人，生酮饮食在中短期内持续产生具有临床意义的体重减轻，通常优于标准低脂饮食。",
    "benefits.card.obesity.improvements": "常见的改善包括：",
    "benefits.card.obesity.list1": "降低腰围",
    "benefits.card.obesity.list2": "降低甘油三酯",
    "benefits.card.obesity.list3": "提高 HDL（“好”）胆固醇",
    "benefits.card.obesity.list4": "适度降低血压",
    "benefits.card.diabetes": "2型糖尿病",
    "benefits.card.diabetes.desc": "对于2型糖尿病（T2D）患者，碳水化合物限制直击根本问题：受损的葡萄糖和胰岛素调节。",
    "benefits.card.diabetes.list1": "显著降低 HbA1c",
    "benefits.card.diabetes.list2": "降低空腹血糖和胰岛素",
    "benefits.card.diabetes.list3": "改善胰岛素敏感性",
    "benefits.card.diabetes.list4": "允许许多患者减少或停用药物",
    "benefits.card.diabetes.warning": "对于服用降糖药物的人来说，没有专业支持的自我指导生酮是有风险的。",
    "benefits.card.nafld": "非酒精性脂肪肝 (NAFLD)",
    "benefits.card.nafld.desc": "新兴证据表明，生酮饮食可以减少肝脏脂肪含量，降低肝酶，并改善整体代谢风险标志物。",
    "benefits.card.nafld.list1": "减少肝脏脂肪含量",
    "benefits.card.nafld.list2": "降低肝酶 (ALT, AST, GGT)",
    "benefits.card.nafld.list3": "减少从头脂肪生成",
    "benefits.card.pcos": "多囊卵巢综合征 (PCOS)",
    "benefits.card.pcos.desc": "在患有 PCOS 和超重/肥胖的女性中，生酮饮食可以促进减肥，改善胰岛素抵抗，并降低雄激素水平。",
    "benefits.card.pcos.list1": "促进减肥",
    "benefits.card.pcos.list2": "改善胰岛素抵抗",
    "benefits.card.pcos.list3": "增强月经规律性",
    "benefits.section2.title": "绝对禁忌症",
    "benefits.contra.warning": "如果您有以下任何情况，请勿在没有专家指导的情况下开始生酮饮食：",
    "benefits.contra.group1": "代谢紊乱",
    "benefits.contra.1": "已知的脂肪酸氧化障碍（例如 CPT-II 缺乏症）",
    "benefits.contra.2": "酮体代谢缺陷",
    "benefits.contra.group2": "器官衰竭",
    "benefits.contra.3": "急性或严重的慢性胰腺炎",
    "benefits.contra.4": "卟啉症或严重肝衰竭",
    "benefits.contra.note": "这些情况很少见，但可以将生酮饮食从有益干预转变为医疗紧急情况。",
    "benefits.section3.title": "相对禁忌症",
    "benefits.caution": "这些情况并不自动排除生酮，但需要经验丰富的医疗监督：",
    "benefits.caution.1": "1型糖尿病",
    "benefits.caution.1.desc": "积极的碳水化合物限制结合胰岛素不足可能引发糖尿病酮症酸中毒 (DKA)。",
    "benefits.caution.1.note": "仅在糖尿病专家的指导下考虑。",
    "benefits.caution.ckd": "慢性肾脏病 (CKD)",
    "benefits.caution.ckd.desc": "生酮与肾脏健康之间的关系是微妙的。",
    "benefits.caution.ckd.list1": "对晚期 CKD 长期安全性的担忧",
    "benefits.caution.ckd.list2": "必须仔细管理蛋白质摄入和电解质",
    "benefits.caution.pregnancy": "怀孕和哺乳期",
    "benefits.caution.pregnancy.desc": "安全数据不足。胎儿发育依赖于可靠的营养供应。最安全的途径是避免严格的生酮饮食。",
    "benefits.caution.ed": "饮食失调史",
    "benefits.caution.ed.desc": "生酮的严格规则可能引发饮食失调模式。除非得到心理健康专家的批准，否则最好避免。",
    "benefits.caution.lipids": "未控制的血脂异常",
    "benefits.caution.lipids.desc": "生酮可能导致某些个体的 LDL 胆固醇显著升高。",
    "benefits.caution.lipids.note": "应有心脏病专家或血脂专家参与。",
    "benefits.bottomline.title": "结论",
    "benefits.bottomline.1": "它针对高胰岛素血症和内脏脂肪等根本原因。",
    "benefits.bottomline.2": "它可以显著改善体重、血糖和肝脏脂肪。",
    "benefits.bottomline.3": "它不适合，或仅谨慎适合某些医疗状况。",
    "benefits.bottomline.action": "您的下一步不应该是明天开始生酮——而应该是接受适当的评估。",
    "benefits.bottomline.step1": "咨询医疗专业人员。",
    "benefits.bottomline.step2": "分享您的完整病史和化验结果。",
    "benefits.bottomline.step3": "讨论生酮策略是否适合您的健康状况。",
    "benefits.bottomline.final": "生酮是一个强大的工具——在正确的人手中非常有效，但并不自动适合每个人。",    // Guide Page
    "guide.back": "返回首页",
    "guide.badge": "实用指南",
    "guide.title": "生酮入门：前两周指南",
    "guide.subtitle": "逐步指南，帮助您度过适应期，管理副作用，并为长期成功做好准备。",
    "guide.step1.title": "医疗准备",
    "guide.step1.history": "审查您的健康史",
    "guide.step1.history.desc": "与您的医疗提供者坐下来审查：",
    "guide.step1.history.list1": "肾脏/肝脏疾病、胰腺炎、胆结石病史",
    "guide.step1.history.list2": "糖尿病（1型或2型）或糖尿病前期",
    "guide.step1.history.list3": "心血管风险因素（心脏病发作、中风）",
    "guide.step1.history.list4": "饮食失调史",
    "guide.step1.meds": "审查药物",
    "guide.step1.meds.desc": "生酮可能会改变您的身体对药物（胰岛素、血压药、利尿剂）的反应。",
    "guide.step1.meds.warning": "如果您正在服药，请勿在未告知医生的情况下开始严格的生酮饮食。",
    "guide.step1.meds.list1": "糖尿病药物（胰岛素、磺脲类药物）",
    "guide.step1.meds.list2": "血压药物",
    "guide.step1.meds.list3": "利尿剂或精神科药物",
    "guide.step1.meds.action": "快速改善可能需要调整剂量以避免低血糖或低血压。",
    "guide.step1.labs": "基线实验室检查",
    "guide.step1.labs.desc": "询问您的提供者进行基线测试：",
    "guide.step1.labs.1": "空腹血糖和HbA1c",
    "guide.step1.labs.2": "血脂面板（总胆固醇、LDL、HDL、甘油三酯）",
    "guide.step1.labs.3": "肝酶（ALT、AST、GGT）",
    "guide.step1.labs.4": "肾功能（肌酐、eGFR）",
    "guide.step1.labs.5": "基本电解质",
    "guide.step1.env": "环境设置",
    "guide.step1.env.1": "选择一个压力较小的开始日期",
    "guide.step1.env.2": "清理厨房中的高碳水化合物食物",
    "guide.step1.env.3": "储备生酮主食（鸡蛋、肉类、蔬菜）",
    "guide.step2.title": "适应期（第1-14天）",
    "guide.step2.intro": "这是您的身体过渡到酮症的地方——从依赖葡萄糖转变为脂肪和酮体代谢。",
    "guide.step2.phase1.title": "第1-3天：耗尽",
    "guide.step2.phase1.desc": "糖原储存排空，导致水分重量迅速减轻。",
    "guide.step2.phase1.s1": "对糖或淀粉的强烈渴望",
    "guide.step2.phase1.s2": "体重秤上的数字迅速下降（主要是水）",
    "guide.step2.phase1.s3": "可能的头痛或易怒",
    "guide.step2.phase2.title": "第4-7天：过渡",
    "guide.step2.phase2.desc": "胰岛素下降，酮体生成增加。",
    "guide.step2.phase2.s1": "饥饿感开始减少",
    "guide.step2.phase2.s2": "能量可能会波动",
    "guide.step2.phase2.s3": "可能会出现酮味呼吸（果味）",
    "guide.step2.phase3.title": "第7-14天：适应",
    "guide.step2.phase3.desc": "早期脂肪适应开始。",
    "guide.step2.phase3.s1": "能量更稳定",
    "guide.step2.phase3.s2": "思维清晰度提高",
    "guide.step2.phase3.s3": "日常活动感觉更顺畅",
    "guide.step2.flu.title": "“生酮流感”",
    "guide.step2.flu.desc": "由于电解质流失和代谢转换引起的暂时性症状：",
    "guide.step2.flu.s1": "头痛和疲劳",
    "guide.step2.flu.s2": "脑雾",
    "guide.step2.flu.s3": "恶心",
    "guide.step2.flu.s4": "头晕",
    "guide.step2.flu.s5": "肌肉痉挛",
    "guide.step2.flu.s6": "易怒",
    "guide.step2.flu.note": "通过补充水分和电解质，大多数症状会很快缓解。",
    "guide.step3.title": "3. 管理副作用",
    "guide.step3.intro": "大多数副作用通过准备是可以控制的。",
    "guide.step3.hydrate": "保持水分",
    "guide.step3.hydrate.desc": "喝水、矿泉水、草药茶和骨汤。",
    "guide.step3.hydration.1": "水和矿泉水",
    "guide.step3.hydration.2": "草本茶",
    "guide.step3.hydration.3": "肉汤（补充盐分）",
    "guide.step3.hydration.rule": "经验法则：如果尿液颜色深或感到头晕，请多喝水。",
    "guide.step3.electrolytes": "电解质",
    "guide.step3.electrolytes.desc": "补充钠、钾和镁。",
    "guide.step3.sodium": "钠",
    "guide.step3.sodium.desc": "给食物加盐。如果需要，喝咸肉汤（除非受限）。",
    "guide.step3.potassium": "钾",
    "guide.step3.potassium.desc": "吃鳄梨、绿叶蔬菜、蘑菇。除非处方，否则避免补充剂。",
    "guide.step3.magnesium": "镁",
    "guide.step3.magnesium.desc": "考虑晚上温和补充。吃南瓜子、杏仁、黑巧克力。",
    "guide.step3.ease": "循序渐进",
    "guide.step3.ease.desc": "如果症状强烈，不要急于求成。",
    "guide.step3.ease.1": "逐渐减少碳水化合物",
    "guide.step3.ease.2": "不要结合剧烈的新锻炼",
    "guide.step3.ease.3": "保持饮食简单",
    "guide.step3.exercise": "调整运动",
    "guide.step3.exercise.1": "高强度运动最初可能会感觉更难",
    "guide.step3.exercise.2": "轻微运动有助于清除脑雾",
    "guide.step3.exercise.3": "适应后表现通常会恢复",
    "guide.step3.exercise.4": "如果感到头晕或不适，请停止",
    "guide.step3.doctor": "何时致电医生",
    "guide.step3.doctor.1": "持续呕吐/恶心",
    "guide.step3.doctor.2": "极度虚弱/胸痛",
    "guide.step3.doctor.3": "极高的血糖/酮体",
    "guide.step3.doctor.4": "严重腹痛",
    "guide.step3.doctor.note": "生酮不应该感觉像紧急情况。",    "guide.longterm.title": "长期成功",
    "guide.longterm.p1": "目标是适合您生活的可持续模式。",
    "guide.longterm.p2": "生酮不是关于完美——它是关于建立一种适合您的身体和生活的饮食方式。",
    "guide.step4.title": "4. 长期成功与陷阱",
    "guide.step4.intro": "一致性胜过完美。",
    "guide.step4.why": "找到您的“为什么”",
    "guide.step4.why.desc": "当您清楚深层原因时，长期改变会更容易。",
    "guide.step4.why.1": "减少药物 / 逆转脂肪肝",
    "guide.step4.why.2": "有精力陪孩子玩耍",
    "guide.step4.why.3": "清晰的头脑用于工作",
    "guide.step4.why.4": "生酮是一种工具，而不是宗教。如果有一天你搞砸了，只需在下一顿饭重新开始。",
    "guide.step4.pitfalls.title": "常见陷阱",
    "guide.step4.pitfalls.1": "过量食用坚果/奶酪（高热量）",
    "guide.step4.pitfalls.2": "加工的“生酮”产品（通常会阻碍进步）",
    "guide.step4.pitfalls.3": "忽视蔬菜（您需要纤维/微量营养素）",
    "guide.step4.pitfalls.4": "痴迷于体重秤（使用腰围或衣服合身度）",
    "guide.conclusion.title": "您的旅程现在开始",
    "guide.conclusion.desc": "生酮不仅仅是一种饮食；它是一种恢复健康的代谢工具。从简单开始，保持一致，倾听您的身体。",
    "guide.conclusion.final": "您能做到的！",

    // BMI Calculator
    "bmi.title": "BMI 计算器",
    "bmi.height": "身高",
    "bmi.weight": "体重",
    "bmi.calculate": "计算 BMI",
    "bmi.result": "您的 BMI",
    "bmi.underweight": "体重过轻",
    "bmi.normal": "正常体重",
    "bmi.overweight": "超重",
    "bmi.obese": "肥胖",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    const langData = translations[language] as Record<string, string>;
    const enData = translations['en'] as Record<string, string>;
    return langData[key] || enData[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
